### ISSUE TITLE
docker_container that exits immediately never changes to "running state"

### ISSUE THREAD

**Issue by b-dean** [chef-cookbooks/docker#1004]
### Cookbook version
4.3.0

### Chef-client version
14.2.0
13.9.4
12.22.5

### Platform Details
CentOS 7 (bento/centos-7.5)
Docker 18.03.0-ce

### Scenario:
Running a container that exits immediately

### Steps to Reproduce:
Run a recipe with these resources:

```ruby
docker_service 'default' do
  install_method 'package'
end

docker_image 'alpine'

docker_container 'alpine' do
  command "sh -c 'echo done'"
end
```

### Expected Result:
The `docker_container` should execute the `:run` action and the container should be stopped.

### Actual Result:
The container is created, starts, and exits, but the `docker_container` resource `:run` action has the following error:

```
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:228:in `wait_running_state'
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:559:in `block (2 levels) in <class:DockerContainer>'
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:554:in `block in <class:DockerContainer>'
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:711:in `call_action'
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:458:in `block in <class:DockerContainer>'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/foo/recipes/default.rb

  7: docker_container 'alpine' do
  8:   command "sh -c 'echo done'"
  9: end

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/foo/recipes/default.rb:7:in `from_file'

docker_container("alpine") do
  action [:run]
  default_guard_interpreter :default
  declared_type :docker_container
  cookbook_name "foo"
  recipe_name "default"
  command ["sh", "-c", "echo done"]
  container_name "alpine"
  connection #<Docker::Connection:0x0000000003073ed0 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>60}>
  repo "alpine"
  env []
  exposed_ports {}
  port_bindings {}
  volumes {}
end

System Info:
------------
chef_version=14.2.0
platform=centos
platform_version=7.5.1804
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/opt/chef/bin/chef-solo
executable=/opt/chef/bin/chef-solo
```

### Workaround:
If I change my command to include some sleeping, so the container won't exit immediately, it works fine.

```ruby
docker_container 'alpine' do
  command "sh -c 'sleep 10 && echo done'"
end
```

**Comment by kapilchouhan99** [comment]
Hi @b-dean , We have verified, it's working fine on the latest version of Docker Cookbook.
Could you please check it on the latest version?
Thanks!!!

**Comment by kapilchouhan99** [comment]
It's working on the latest version of the Docker cookbook, So closing this issue.

If you are still facing this issue, you can reopen it.

Thanks!
