### ISSUE TITLE
env_file, cookbook compilation phase, exception -  file not found

### ISSUE THREAD

**Issue by isuftin** [chef-cookbooks/docker#1079]
### Cookbook version
v4.9.3

### Chef-client version
14.13.11

### Platform Details
CentOS 7 running on AWS EC2

### Scenario:
Run the container recipe and provide env_file attribute for a file that does not yet exist on the filesystem.

I am running the Docker cookbook via a wrapper cookbook I wrote: https://github.com/USGS-CIDA/chef-cookbook-owi-docker/blob/master/recipes/docker_container.rb

Part of my wrapper cookbook includes a recipe that pulls files down from remote locations: https://github.com/USGS-CIDA/chef-cookbook-owi-docker/blob/master/recipes/file_utils.rb

I am trying to run file_utils *then* docker_container in order because on a new system,the file_utils recipe will pull down a config file from s3 which I then use as the env_file attribute within the container recipe.

Unfortunately, during the cookbook compile phase, I am seeing the following error:

`Errno::ENOENT: No such file or directory @ rb_sysopen - /root/configuration/sonarqube.env`

And this stack trace:

```
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:315:in `readlines'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:315:in `block in coerce_env_file'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:315:in `map'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:315:in `coerce_env_file'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:25:in `block in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:696:in `instance_exec'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:696:in `exec_in_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:493:in `coerce'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:725:in `coerce_and_validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:709:in `input_to_stored_value'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:428:in `set'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:350:in `call'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/property.rb:571:in `env_file'
/var/chef/cache/cookbooks/owi_docker/recipes/docker_container.rb:27:in `block (2 levels) in from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_builder.rb:66:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_builder.rb:66:in `build'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/dsl/resources.rb:38:in `docker_container'
/var/chef/cache/cookbooks/owi_docker/recipes/docker_container.rb:8:in `block in from_file'
/var/chef/cache/cookbooks/owi_docker/recipes/docker_container.rb:7:in `each'
/var/chef/cache/cookbooks/owi_docker/recipes/docker_container.rb:7:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/cookbook_version.rb:199:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/run_context.rb:350:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/run_context/cookbook_compiler.rb:166:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/run_context/cookbook_compiler.rb:163:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/run_context/cookbook_compiler.rb:163:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/run_context.rb:199:in `load'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:515:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:321:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:309:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:309:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:274:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/client.rb:484:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/client.rb:473:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/client.rb:472:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/client.rb:472:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/client.rb:456:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/bin/chef-client:25:in `<top (required)>'
```

What this tells me is that the compile phase for the Docker cookbook checks if a file specified in env_file is present. I don't expect this file to exist during the compile phase. I expect this file to appear during a normal Chef run.

Thoughts?

**Comment by kapilchouhan99** [comment]
@isuftin Could you please check it on the latest version of the Docker cookbook?
because it might be fixed on the latest version.

**Comment by kapilchouhan99** [comment]
It's working on the latest version of the Docker cookbook, So closing this issue.

If you are still facing this issue, you can reopen it.

Thanks!
