### ISSUE TITLE
handle network_mode changes with existing containers

### ISSUE THREAD

**Issue by manuelmazzuola** [chef-cookbooks/docker#542]
Issue with docker 1.9.0

 ```
 Docker::Error::ConflictError
           ----------------------------
           Conflicting options: -h and the network mode (--net)
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:48:in `rescue in 
request'
           /tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
           /tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 l
evels) in <class:Connection>'
           /tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/container.rb:234:in `create'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:181:in `block (3 levels) in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `call'
           /tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `with_retries'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:180:in `block (2 levels) in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:50:in `converge_if_ch
anged'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:177:in `block in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:159:in `call_action'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:272:in `block in <class:DockerContainer>'

   docker_container("sample-app") do
             action [:run]
             updated true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_container
             cookbook_name :"cd-docker"
             recipe_name "default"
             repo "cloudesire/sample-app"
             tag "0.0.1"
             container_name "sample-app"
             detach true
             network_mode "host"
             env ["CLOUDESIRE_VHOST=test-cd-docker.appstaging.cloudesire.local", "DEFAULT_PORT_5000_TCP_PORT=3333", "DEFAULT_PO
RT_5000_TCP_ADDRESS=localhost"]
             connection #<Docker::Connection:0x00000007845970 @url="unix:///", @options={:socket=>"/var/run/docker.sock", "read
_timeout"=>60}>
             log_driver "json-file"
             restart_policy "no"
             security_opts [""]
             signal "SIGKILL"
           end

```

**Comment by someara** [comment]
Does this still happen in v2.2.6?

If so, let's come up with a failing resource to put in here:

https://github.com/someara/chef-docker/blob/1c738b5c72ea7ec9f6c98f7aefe9bc25c8718c59/test/cookbooks/docker_test/recipes/container.rb

**Comment by chasebolt** [comment]
when using NetworkMode, Hostname and MacAddress aren't allowed to be set. Before 1.9.0 the api just ignored it while the cli complained about it.

**Comment by someara** [comment]
Closing this here, referencing #557.

**Comment by manuelmazzuola** [comment]
I'm still experiencing this isuee with the latest `2.3.16` cookbook.
```
[staging-nxt] out:   * docker_container[logstash-forwarder] action run
[staging-nxt] out:     - stopping logstash-forwarder 
[staging-nxt] out:     - deleting logstash-forwarder
[staging-nxt] out:     ================================================================================
[staging-nxt] out:     Error executing action `run` on resource 'docker_container[logstash-forwarder]'
[staging-nxt] out:     ================================================================================
[staging-nxt] out:     
[staging-nxt] out:     Docker::Error::ConflictError
[staging-nxt] out:     ----------------------------
[staging-nxt] out:     Conflicting options: -h and the network mode (--net)
[staging-nxt] out:     

[staging-nxt] out:     docker_container("logstash-forwarder") do
[staging-nxt] out:       params {:name=>"logstash-forwarder", :image_name=>"digitalwonderland/logstash-forwarder", :image_version=>"latest",
:image_latest=>false, :port=>[], :env=>"LOGSTASH_HOST=staging-nxt.cloudesire.com:5043",  :subscribes=>[], :action=>nil, :command=>nil, :privileged=>false}
[staging-nxt] out:       action [:run]
[staging-nxt] out:       retries 0
[staging-nxt] out:       retry_delay 2
[staging-nxt] out:       default_guard_interpreter :default
[staging-nxt] out:       declared_type :docker_container
[staging-nxt] out:       cookbook_name :"cd-infrastructure"
[staging-nxt] out:       recipe_name "docker-logstash-forwarder"
[staging-nxt] out:       detach true
[staging-nxt] out:       container_name "logstash-forwarder"
[staging-nxt] out:       repo "digitalwonderland/logstash-forwarder"
[staging-nxt] out:       tag "latest"
[staging-nxt] out:       network_mode "host"
[staging-nxt] out:       timeout 15
[staging-nxt] out:       restart_policy "always"
[staging-nxt] out:       restart_maximum_retry_count 2
[staging-nxt] out:       connection #<Docker::Connection:0x0000000515e2a8 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_
timeout=>60}>
[staging-nxt] out:     end
```

```
ubuntu@staging-nxt:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
```

**Comment by chasebolt** [comment]
ok let's see if we can debug this.

on the docker box install socat and then run this https://gist.github.com/chasebolt/3e58bc05203a6fcf5d71, it will run in the foreground.

gist all the output.

**Comment by someara** [comment]
re-opening

**Comment by manuelmazzuola** [comment]
The relevant part should be this one.
```
 2015/12/18 11:04:54.923467  length=1461 from=0 to=1460
POST /v1.16/containers/create?name=logstash-forwarder HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: application/json\r
Host: /var/run/docker.sock\r
Content-Length: 1274\r
\r
{"Image":"digitalwonderland/logstash-forwarder:latest","Labels":{"License":"GPLv2","Vendor":"CentOS"},"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Domainname":"","Entrypoint":["/usr/local/bin/d
ocker-logstash-forwarder"],"Env":["LOGSTASH_HOST=staging-nxt.cloudesire.com:5043"],"ExposedPorts":{},"Hostname":"staging-nxt","MacAddress":"","NetworkDisabled":false,"OpenStdin":false,"StdinOnce":false,"Tty":fal
se,"User":"","Volumes":{"/var/lib/docker:/var/lib/docker:ro":{},"/var/run/docker.sock:/var/run/docker.sock":{},"/srv/logstash-forwarder/certs/forwarder.crt:/mnt/logstash-forwarder/logstash-forwarder.crt":{},"/sr
v/logstash-forwarder/certs/forwarder.key:/mnt/logstash-forwarder/logstash-forwarder.key":{}},"WorkingDir":"","HostConfig":{"Binds":["/var/lib/docker:/var/lib/docker:ro","/var/run/docker.sock:/var/run/docker.sock
","/srv/logstash-forwarder/certs/forwarder.crt:/mnt/logstash-forwarder/logstash-forwarder.crt","/srv/logstash-forwarder/certs/forwarder.key:/mnt/logstash-forwarder/logstash-forwarder.key"],"CgroupParent":"","Cpu
Shares":0,"CpusetCpus":"","Devices":[],"DnsSearch":[],"Memory":0,"MemorySwap":0,"NetworkMode":"host","Privileged":false,"PortBindings":{},"PublishAllPorts":false,"RestartPolicy":{"Name":"always","MaximumRetryCou
nt":2}}}< 2015/12/18 11:04:54.925270  length=206 from=0 to=205
HTTP/1.1 409 Conflict\r
Content-Type: text/plain; charset=utf-8\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:04:54 GMT\r
Content-Length: 53\r
\r
Conflicting options: -h and the network mode (--net)
```

Who send the Hostname parameter `staging-nxt` ?

The relative resource is
```
docker_container "logstash-forwarder" do
    detach true
    container_name "logstash-forwarder"
    repo "digitalwonderland/logstash-forwarder"
    tag "latest"
    env ["THEENVS=blabla"]
    network_mode "host"
    timeout 15
    restart_policy 'always'
    restart_maximum_retry_count 2
    action [:run]
  end
```

**Comment by manuelmazzuola** [comment]
I've found something strange.
The container `logstash-forwarder` already exists on the machine, provisioned with the old docker 1.7.1.
`docker inspect` shows the Hostname populated with `staging-nxt`.
When chef run it stop, delete and recreate the container and fails with the errore above.
But if I manually delete the container `docker rm -f logstash-forwarder` and the run chef, the container is created successfully.

socat log If the container already exists:
```
> 2015/12/18 11:43:34.471134  length=230 from=0 to=229
POST /v1.16/containers/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828/stop?t=-1 HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: application/json\r
Host: /var/run/docker.sock\r
Content-Length: 2\r
\r
{}< 2015/12/18 11:43:34.557059  length=94 from=0 to=93
HTTP/1.1 204 No Content\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:43:34 GMT\r
\r
> 2015/12/18 11:43:34.559080  length=144 from=0 to=143
GET /v1.16/containers/registrator/json HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: text/plain\r
Host: /var/run/docker.sock\r
\r
< 2015/12/18 11:43:34.560239  length=3391 from=0 to=3390
HTTP/1.1 200 OK\r
Content-Type: application/json\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:43:34 GMT\r
Transfer-Encoding: chunked\r
\r
ca1\r
{"Id":"960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828","Created":"2015-12-18T11:38:25.00331065Z","Path":"/bin/registrator","Args":["consul://127.0.0.1:8500","-resync","60"],"State":{"Status":"e
xited","Running":false,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":2,"Error":"","StartedAt":"2015-12-18T11:38:25.13916787Z","FinishedAt":"2015-12-18T11:43:34.516800311Z"},
"Image":"6ecdc1a91b084be73daf850b7938ab2819b1aab75579f26bf40fd97d97b90d3c","ResolvConfPath":"/var/lib/docker/containers/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828/resolv.conf","HostnamePath
":"/var/lib/docker/containers/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828/hostname","HostsPath":"/var/lib/docker/containers/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828/h
osts","LogPath":"/var/lib/docker/containers/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828-json.log","Name":"/registrator","Rest
artCount":0,"Driver":"aufs","ExecDriver":"native-0.2","MountLabel":"","ProcessLabel":"","AppArmorProfile":"","ExecIDs":null,"HostConfig":{"Binds":["/var/run/docker.sock:/tmp/docker.sock"],"ContainerIDFile":"","L
xcConf":null,"Memory":0,"MemoryReservation":0,"MemorySwap":-1,"KernelMemory":0,"CpuShares":0,"CpuPeriod":0,"CpusetCpus":"","CpusetMems":"","CpuQuota":0,"BlkioWeight":0,"OomKillDisable":false,"MemorySwappiness":n
ull,"Privileged":false,"PortBindings":{},"Links":null,"PublishAllPorts":false,"Dns":null,"DnsOptions":null,"DnsSearch":null,"ExtraHosts":null,"VolumesFrom":null,"Devices":null,"NetworkMode":"host","IpcMode":"","
PidMode":"","UTSMode":"","CapAdd":null,"CapDrop":null,"GroupAdd":null,"RestartPolicy":{"Name":"always","MaximumRetryCount":2},"SecurityOpt":null,"ReadonlyRootfs":false,"Ulimits":null,"LogConfig":{"Type":"json-fi
le","Config":{}},"CgroupParent":"","ConsoleSize":[0,0],"VolumeDriver":""},"GraphDriver":{"Name":"aufs","Data":null},"Volumes":{"/tmp/docker.sock":"/var/run/docker.sock","/var/run/docker.sock:/tmp/docker.sock":"/
var/lib/docker/volumes/d237d11dc65fb81e06469909aac5d372fc4c124bcedebc1a21ff883ee85ac069/_data"},"VolumesRW":{"/tmp/docker.sock":true,"/var/run/docker.sock:/tmp/docker.sock":true},"Config":{"Hostname":"staging-nx
t","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi
n"],"Cmd":["consul://127.0.0.1:8500","-resync","60"],"Image":"gliderlabs/registrator:v6","Volumes":{"/var/run/docker.sock:/tmp/docker.sock":{}},"WorkingDir":"","Entrypoint":["/bin/registrator"],"OnBuild":null,"L
abels":{},"MacAddress":"","NetworkDisabled":false,"ExposedPorts":null,"VolumeDriver":"","Memory":0,"MemorySwap":-1,"CpuShares":0,"Cpuset":""},"NetworkSettings":{"Bridge":"","SandboxID":"","HairpinMode":false,"Li
nkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":null,"SandboxKey":"","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":
0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":""}}
\r
0\r
\r
> 2015/12/18 11:43:34.581718  length=234 from=0 to=233
DELETE /v1.16/containers/960efd2ef3b6c95752f7bde63e339a6103146b7b983fa044bbbf3a7462516828?force=false&v=false HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: text/plain\r
Host: /var/run/docker.sock\r
Content-Length: 0\r
\r
< 2015/12/18 11:43:34.628799  length=94 from=0 to=93
HTTP/1.1 204 No Content\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:43:34 GMT\r
\r
> 2015/12/18 11:43:34.633074  length=888 from=0 to=887
POST /v1.16/containers/create?name=registrator HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: application/json\r
Host: /var/run/docker.sock\r
Content-Length: 709\r
\r
{"Image":"gliderlabs/registrator:v6","Labels":{},"Cmd":["consul://127.0.0.1:8500","-resync","60"],"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Domainname":"","Entrypoint":["/bin/registrator"],"
Env":[],"ExposedPorts":{},"Hostname":"staging-nxt","MacAddress":"","NetworkDisabled":false,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{"/var/run/docker.sock:/tmp/docker.sock":{}},"Workin
gDir":"","HostConfig":{"Binds":["/var/run/docker.sock:/tmp/docker.sock"],"CgroupParent":"","CpuShares":0,"CpusetCpus":"","Memory":0,"MemorySwap":-1,"NetworkMode":"host","Privileged":false,"PortBindings":{},"Publ
ishAllPorts":false,"RestartPolicy":{"Name":"always","MaximumRetryCount":2}}}< 2015/12/18 11:43:34.636012  length=206 from=0 to=205
HTTP/1.1 409 Conflict\r
Content-Type: text/plain; charset=utf-8\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:43:34 GMT\r
Content-Length: 53\r
\r
Conflicting options: -h and the network mode (--net)
```

socat log If the container doesn't exists:
```
> 2015/12/18 11:50:23.962284  length=144 from=0 to=143
GET /v1.16/containers/registrator/json HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: text/plain\r
Host: /var/run/docker.sock\r
\r
< 2015/12/18 11:50:23.963440  length=178 from=0 to=177
HTTP/1.1 404 Not Found\r
Content-Type: text/plain; charset=utf-8\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:50:23 GMT\r
Content-Length: 24\r
\r
no such id: registrator
> 2015/12/18 11:50:23.965219  length=144 from=0 to=143
GET /v1.16/containers/registrator/json HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: text/plain\r
Host: /var/run/docker.sock\r
\r
< 2015/12/18 11:50:23.966358  length=178 from=0 to=177
HTTP/1.1 404 Not Found\r
Content-Type: text/plain; charset=utf-8\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:50:23 GMT\r
Content-Length: 24\r
\r
no such id: registrator
> 2015/12/18 11:50:23.968056  length=144 from=0 to=143
GET /v1.16/containers/registrator/json HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: text/plain\r
Host: /var/run/docker.sock\r
\r
< 2015/12/18 11:50:23.969073  length=178 from=0 to=177
HTTP/1.1 404 Not Found\r
Content-Type: text/plain; charset=utf-8\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:50:23 GMT\r
Content-Length: 24\r
\r
no such id: registrator
> 2015/12/18 11:50:23.970491  length=144 from=0 to=143
GET /v1.16/containers/registrator/json HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: text/plain\r
Host: /var/run/docker.sock\r
\r
< 2015/12/18 11:50:23.971779  length=178 from=0 to=177                                                                                                                                                  [1087/1473]
HTTP/1.1 404 Not Found\r
Content-Type: text/plain; charset=utf-8\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:50:23 GMT\r
Content-Length: 24\r
\r
no such id: registrator
> 2015/12/18 11:50:23.990336  length=818 from=0 to=817
POST /v1.16/containers/create?name=registrator HTTP/1.1\r
User-Agent: Swipely/Docker-API 1.24.1\r
Content-Type: application/json\r
Host: /var/run/docker.sock\r
Content-Length: 639\r
\r
{"Image":"gliderlabs/registrator:v6","Cmd":["consul://127.0.0.1:8500","-resync","60"],"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Domainname":"","Env":[],"ExposedPorts":{},"NetworkDisabled":fa
lse,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{"/var/run/docker.sock:/tmp/docker.sock":{}},"HostConfig":{"Binds":["/var/run/docker.sock:/tmp/docker.sock"],"CgroupParent":"","CpuShares":
0,"CpusetCpus":"","LogConfig":{"Type":"json-file"},"Memory":0,"MemorySwap":-1,"NetworkMode":"host","Privileged":false,"PortBindings":{},"PublishAllPorts":false,"RestartPolicy":{"Name":"always","MaximumRetryCount
":2}}}< 2015/12/18 11:50:24.054790  length=233 from=0 to=232
HTTP/1.1 201 Created\r
Content-Type: application/json\r
Server: Docker/1.9.1 (linux)\r
Date: Fri, 18 Dec 2015 11:50:24 GMT\r
Content-Length: 90\r
\r
{"Id":"a2e6fa6f91501e7f5b6e68a533345d5bd0a789dbe2a7d41c4c33307899821611","Warnings":null}
```

**Comment by chasebolt** [comment]
Ahhh! This all makes perfect sense now.

Since a docker container with the same name already exists, https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb#L117-L142, load_current_value is actually pulling in the running container's config and setting the values for the docker_container resource. 

Because hostname is not set on the docker_container and there is no default property, the setting from load_current_value persists. I think the correct fix here is to only set the resource property if the resource `property_is_set?` evals true.

I'll see if I can get this replicated in test-kitchen and if this idea fixes your issue.

**Comment by chasebolt** [comment]
Just an update. I am able to replicate what I posted above. Working out the best way to implement a fix in the load_current_resource. Will pick it back up on Monday.

**Comment by manuelmazzuola** [comment]
Thank you @chasebolt 
But, as you can see from the socat logs, a `DELETE` action arrives and docker's answer is `204 no content` so the container is actualy removed and then recreated, isn't it ?
Why this behaviour even if the container is being deleted ?

**Comment by chasebolt** [comment]
`load_current_value` runs at the very first part of creating the `docker_container` resource. So before it does anything, it looks for a container with the name name as the `docker_container` and then loads in all the config values. After that it overwrites the values with the properties on the resource. Then it runs through the actions, delete/create/etc.

**Comment by manuelmazzuola** [comment]
@chasebolt any updates?
btw happy holidays

**Comment by chasebolt** [comment]
Currently in the Philippines for the holidays. Came to a block on this before I left.

I think the solution is we need to set a default on every property that is a desired_state. I would find all the default values by grabbing the container create json (using socat method) that the docker cli passes. And not set load_current_value on desired_state: false properties.

This _should_ fix the issue but I won't be able to test this until I get back around Jan 10th. Feel free to give a stab at it!

**Comment by someara** [comment]
Verified with pry - https://gist.github.com/someara/2a7a06e2459a75f3612d#file-gistfile1-txt-L25
Adding coerce_hostname in a12066c58bbe6ab921db54754565b447018f1a9e
Released as 2.3.20

**Comment by someara** [comment]
had to revert that commit.. this is still busted as of 2.3.21.

this is a dupe with #572 ... reopening there.

**Comment by someara** [comment]
I guess it would only be the properties

**Comment by someara** [comment]
Added a "parsed_hostname" to hack around this in #572... leaving this open until we handle the rest of the network_mode related properties dns, dns_search, mac_address, and extra_hosts

**Comment by manuelmazzuola** [comment]
`2.3.22` version works fine, thanks
