### ISSUE TITLE
Vendored docker causing issues

### ISSUE THREAD

**Issue by scalp42** [chef-cookbooks/docker#591]
I just ran into this issue with sensu (not using embedded ruby), but not sure what's the exact issue:

```
  * service[sensu-client] action restart

    ================================================================================
    Error executing action `restart` on resource 'service[sensu-client]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /etc/init.d/sensu-client restart ----
    STDOUT: * Stopping sensu-client
     * sensu-client is stopped
     * Starting sensu-client
       ...fail!
    STDERR: /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/stub_specification.rb:75:in `initialize': Permission denied @ rb_sysopen - /var/chef/cache/cookbooks/docker/files/default/vendor/specifications/docker-api-1.24.0.gemspec (Errno::EACCES)
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/stub_specification.rb:75:in `open'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/stub_specification.rb:75:in `data'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/stub_specification.rb:178:in `valid?'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:731:in `block in each_stub'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:723:in `block (2 levels) in each_gemspec'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:722:in `each'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:722:in `block in each_gemspec'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:721:in `each'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:721:in `each_gemspec'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:729:in `each_stub'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:748:in `stubs'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:273:in `matching_specs'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:295:in `to_specs'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    	from /opt/sensu/bin/sensu-client:22:in `<main>'
    ---- End output of /etc/init.d/sensu-client restart ----
    Ran /etc/init.d/sensu-client restart returned 1
```

This is owned by root:

```
-rw------- 1 root root 2.4K Dec 17 02:05 /var/chef/cache/cookbooks/docker/files/default/vendor/specifications/docker-api-1.24.0.gemspec
```

Will open an issue on sensu side as well, but feel free to close if it has nothing to do :smile:

**Comment by scalp42** [comment]
I tested with `2.3.14` and it's working fine.

**Comment by someara** [comment]
There was a brief moment where it was using unshift instead of mimicking
the chef_gem load technique.
Glad to hear this is fixed up already! =)

-s

**Comment by someara** [comment]
er, push

**Comment by scalp42** [comment]
Wait @someara , I think there's some confusion:

`2.3.15` and up are **not** working.

**Comment by someara** [comment]
Any ideas about this one @jkeiser ?

**Comment by scalp42** [comment]
@someara  @jkeiser Running into another issue with route53 cookbook for example:

```
  * route53_record[blabla.example.com] action create/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:3: warning: already initialized constant Excon::VERSION
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:3: warning: previous definition of VERSION was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:5: warning: already initialized constant Excon::CR_NL
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:5: warning: previous definition of CR_NL was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:7: warning: already initialized constant Excon::DEFAULT_CA_FILE
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:7: warning: previous definition of DEFAULT_CA_FILE was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:9: warning: already initialized constant Excon::DEFAULT_CHUNK_SIZE
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:9: warning: previous definition of DEFAULT_CHUNK_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:16: warning: already initialized constant Excon::DEFAULT_RETRY_LIMIT
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:16: warning: previous definition of DEFAULT_RETRY_LIMIT was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:18: warning: already initialized constant Excon::FORCE_ENC
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:18: warning: previous definition of FORCE_ENC was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:20: warning: already initialized constant Excon::HTTP_1_1
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:20: warning: previous definition of HTTP_1_1 was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:22: warning: already initialized constant Excon::HTTP_VERBS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:22: warning: previous definition of HTTP_VERBS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:24: warning: already initialized constant Excon::HTTPS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:24: warning: previous definition of HTTPS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:26: warning: already initialized constant Excon::NO_ENTITY
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:26: warning: previous definition of NO_ENTITY was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:28: warning: already initialized constant Excon::REDACTED
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:28: warning: previous definition of REDACTED was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:30: warning: already initialized constant Excon::UNIX
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:30: warning: previous definition of UNIX was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:32: warning: already initialized constant Excon::USER_AGENT
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:32: warning: previous definition of USER_AGENT was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:34: warning: already initialized constant Excon::VERSIONS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:34: warning: previous definition of VERSIONS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:36: warning: already initialized constant Excon::VALID_REQUEST_KEYS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:36: warning: previous definition of VALID_REQUEST_KEYS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:63: warning: already initialized constant Excon::VALID_CONNECTION_KEYS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:63: warning: previous definition of VALID_CONNECTION_KEYS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/constants.rb:110: warning: already initialized constant Excon::DEFAULTS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/constants.rb:110: warning: previous definition of DEFAULTS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/utils.rb:5: warning: already initialized constant Excon::Utils::CONTROL
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/utils.rb:5: warning: previous definition of CONTROL was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/utils.rb:6: warning: already initialized constant Excon::Utils::DELIMS
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/utils.rb:6: warning: previous definition of DELIMS was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/utils.rb:7: warning: already initialized constant Excon::Utils::UNWISE
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/utils.rb:7: warning: previous definition of UNWISE was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/utils.rb:8: warning: already initialized constant Excon::Utils::NONASCII
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/utils.rb:8: warning: previous definition of NONASCII was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/utils.rb:9: warning: already initialized constant Excon::Utils::UNESCAPED
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/utils.rb:9: warning: previous definition of UNESCAPED was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/utils.rb:10: warning: already initialized constant Excon::Utils::ESCAPED
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/utils.rb:10: warning: previous definition of ESCAPED was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/headers.rb:4: warning: already initialized constant Excon::Headers::SENTINEL
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/headers.rb:4: warning: previous definition of SENTINEL was here
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:3: warning: already initialized constant Excon::SSLSocket::HAVE_NONBLOCK
/var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:3: warning: previous definition of HAVE_NONBLOCK was here


    ================================================================================
    Error executing action `create` on resource 'route53_record[blabla.example.com]'
    ================================================================================

    SystemStackError
    ----------------
    stack level too deep

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/headers.rb:33

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/gz-base/recipes/route53.rb

     28:     route53_record 'create CNAME record' do
     29:       name node['set_fqdn']
     30:       value ec2_hostname
     31:       type 'CNAME'
     32:       zone_id zone_id
     33:       aws_access_key_id node['route53']['aws_access_key_id']
     34:       aws_secret_access_key node['route53']['aws_secret_access_key']
     35:       ttl 60
     36:       overwrite true
     37:       action :create
     38:     
     39:     end
     40:   end
```

**Comment by scalp42** [comment]
I'm looking at route53 forks in emergency as it's a blocker for us. Some use `aws-sdk` which should remove the depdency on `excon` :sake:

**Comment by mrlamroger** [comment]
Hi,

Looks like we're running into the same issue. I tracked it down to GEM_PATH being polluted and believe reverting back to 12.3.14 will resolve the issue. 

https://github.com/chef-cookbooks/docker/issues/592

**Comment by someara** [comment]
Reverted offending commit. Released as v2.3.17

**Comment by scalp42** [comment]
Still running into the issue with excon unfortunately if you have any lwrp that relies on it (or fog).

Moved to `aws-sdk` but I suspect it's still broken.

Thanks for the quick response @someara much much appreciated as always!

**Comment by someara** [comment]
I'll give the gem loading technique another crack over the next few weeks

**Comment by kri5** [comment]
Any news on this issue?
