### ISSUE TITLE
Suggestion: Change README.md to say Chef 12.5.x+ is required due to "NoMethodError undefined method `shell_out'" in test-kitchen converge

### ISSUE THREAD

**Issue by bossjones** [chef-cookbooks/docker#618]
Hi guys,

First of all great work with this cookbook, the documentation is very clear and easy to understand. This is simply a suggestion to modify the `README.md` to indicate that you need to have chef 12.5.x+ installed in order to leverage the `shell_out` command instead of simply `12.0.0`. Initially I had `chef-12.2.1-1` installed on a test-kitchen vagrant instance. While running a converge I received this error: 

```           ================================================================================
           Error executing action `start` on resource 'docker_service_manager_systemd[default]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `shell_out' for DockerCookbook::DockerServiceManagerSystemd

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_service.rb:40:in `docker_version'
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_service.rb:94:in `docker_major_version'
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_service.rb:100:in `docker_daemon_arg'
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_service.rb:108:in `docker_daemon_cmd'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb:54:in `block (2 levels) in <class:DockerServiceManagerSystemd>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:109:in `build_resource'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:67:in `declare_resource'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb:46:in `block in <class:DockerServiceManagerSystemd>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/bedocker/recipes/default.rb

            18: docker_service_manager_systemd 'default' do
            19:   host ['unix:///var/run/docker.sock', 'tcp://127.0.0.1:2376']
            20:   action :start
            21: end
            22:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/bedocker/recipes/default.rb:18:in `from_file'

           docker_cookbook::_docker_service_manager_systemd("default") do
             action [:start]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_service_manager_systemd
             cookbook_name "bedocker"
             recipe_name "default"
             host ["unix:///var/run/docker.sock", "tcp://127.0.0.1:2376"]
           end
```

I logged into the instance and upgraded chef to `chef-12.5.1-1.el7`, re-ran my converge and everything worked. Later on I upgraded to `chef-12.6.0-1.el7` and that obviously worked as well ( btw this is a CentOS 7.2 image ).

Hopefully this helps someone who might have seen the same issue.

**Comment by someara** [comment]
Hello!

The dependency on compat_resource is supposed to let it work back to 12.0.0... so I'd consider this a bug.

@jkeiser any ideas off the top of your head?

-s

**Comment by someara** [comment]
I ended up making the change to the README. Thanks!
