### ISSUE TITLE
ValidationFailed with network_mode=host but without forbidden attributes specified

### ISSUE THREAD

**Issue by gionn** [chef-cookbooks/docker#626]
Hi,

I am getting a validation error, but I am not using any of the specified attributes on docker_container.

```
         * docker_container[app_net_host] action run                                                                                                                                                       [209/8073]
           
           ================================================================================
           Error executing action `run` on resource 'docker_container[app_net_host]'
           ================================================================================
           
           Chef::Exceptions::ValidationFailed
           ----------------------------------
           Cannot specify hostname, dns, dns_search, mac_address, or extra_hosts when network_mode is host.
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:198:in `validate_container_create'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:317:in `block in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/cd-docker/recipes/default.rb
           
           125:   docker_container application_name do
           126:     repo image
           127:     tag version if version
           128:     container_name application_name
           129:     detach true
           130:     network_mode network_name
           131:     env envs
           132:     port ports
           133:     volume volumes
           134:     binds volumes
           135:     restart_policy 'always'
           136:     kill_after 30
           137:     privileged privileged_flag
           138:     command commandline if commandline
           139:   end
           140: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/cd-docker/recipes/default.rb:125:in `block in from_file'
           
           docker_container("app_net_host") do
             action [:run]
             updated true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_container
             cookbook_name :"cd-docker"
             recipe_name "default"
             repo "jmvrbanac/hastebin"
             container_name "app_net_host"
             detach true
             network_mode "host"
             env ["CLOUDESIRE_VHOST=nethost.cloudesire.local"]
             exposed_ports {"7777/tcp"=>{}}
             port_bindings {"7777/tcp"=>[{"HostIp"=>"0.0.0.0", "HostPort"=>"31001"}]}
             port ["31001:7777"]
             volumes_binds ["/etc/localtime:/etc/localtime:ro"]
             restart_policy "always"
             kill_after 30
             connection #<Docker::Connection:0x000000060204d0 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>60}>
             tag "latest"
             log_driver "json-file"
             signal "SIGTERM"
           end
```

**Comment by gionn** [comment]
A second converge without any changes completes without error, so maybe there is some strange interaction on the first run (involving docker service install)

```
docker_service 'default' do
  tls false
  storage_driver 'overlay'
  group 'docker'
  version '1.9.1'
  service_manager 'auto'
  install_method 'package'
  auto_restart true
  log_level :debug
  iptables false
  action [:create, :start]
end
```

**Comment by chasebolt** [comment]
Do you happen to have created a container previously with network mode set? Or maybe a container with the same name created manually?

**Comment by gionn** [comment]
Yes, the first two containers are using a custom defined network, previously created via `docker network create whatever`, and started setting `network_mode 'whatever'`.

Then I've added a third container with network_mode=host and failures started.

Tried upgrading from 2.4.4 to 2.4.10, nothing changed.

**Comment by gionn** [comment]
Uhm, just tried to add a separated suite, and container alone with `network_mode 'host'` continue to fails.

Is running container with `network_mode 'host'` totally broken in latest release?

```
I, [2016-02-04T14:47:38.292828 #31145]  INFO -- cd-docker-nethost-ubuntu-1404: Recipe: cd-docker::default
I, [2016-02-04T14:48:42.061094 #31145]  INFO -- cd-docker-nethost-ubuntu-1404: 
I, [2016-02-04T14:48:42.061742 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     - Pull image jmvrbanac/hastebin:latest
I, [2016-02-04T14:48:42.272477 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:   * docker_container[app_net_host] action redeploy
I, [2016-02-04T14:48:42.272587 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     - create app_net_host
I, [2016-02-04T14:48:42.272624 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set container_name              to "app_net_host"
I, [2016-02-04T14:48:42.272672 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set repo                        to "jmvrbanac/hastebin"
I, [2016-02-04T14:48:42.272701 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set tag                         to "latest" (default value)
I, [2016-02-04T14:48:42.272740 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set command                     to nil (default value)
I, [2016-02-04T14:48:42.272779 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set cap_add                     to nil (default value)
I, [2016-02-04T14:48:42.272825 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set cap_drop                    to nil (default value)
I, [2016-02-04T14:48:42.272856 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set cgroup_parent               to "" (default value)
I, [2016-02-04T14:48:42.272881 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set cpu_shares                  to 0 (default value)
I, [2016-02-04T14:48:42.272903 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set cpuset_cpus                 to "" (default value)
I, [2016-02-04T14:48:42.272947 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set devices                     to [] (default value)
I, [2016-02-04T14:48:42.272969 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set dns                         to [] (default value)
I, [2016-02-04T14:48:42.272991 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set dns_search                  to [] (default value)
I, [2016-02-04T14:48:42.273015 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set domain_name                 to "" (default value)
I, [2016-02-04T14:48:42.273037 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set entrypoint                  to nil (default value)
I, [2016-02-04T14:48:42.273059 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set env                         to ["CLOUDESIRE_VHOST=nethost.cloudesire.local"]
I, [2016-02-04T14:48:42.273085 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set extra_hosts                 to nil (default value)
I, [2016-02-04T14:48:42.273111 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set exposed_ports               to {"7777/tcp"=>{}}
I, [2016-02-04T14:48:42.273136 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set hostname                    to nil (default value)
I, [2016-02-04T14:48:42.273159 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set ipc_mode                    to "" (default value)
I, [2016-02-04T14:48:42.273185 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set labels                      to {} (default value)
I, [2016-02-04T14:48:42.273210 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set links                       to nil (default value)
I, [2016-02-04T14:48:42.273260 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set log_driver                  to "json-file" (default value)
I, [2016-02-04T14:48:42.273290 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set log_opts                    to nil (default value)
I, [2016-02-04T14:48:42.273337 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set mac_address                 to nil (default value)
I, [2016-02-04T14:48:42.273361 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set memory                      to 0 (default value)
I, [2016-02-04T14:48:42.273391 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set memory_swap                 to 0 (default value)
I, [2016-02-04T14:48:42.273423 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set network_disabled            to false (default value)
I, [2016-02-04T14:48:42.273453 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set network_mode                to "host"
I, [2016-02-04T14:48:42.273483 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set outfile                     to nil (default value)
I, [2016-02-04T14:48:42.273510 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set port_bindings               to {"7777/tcp"=>[{"HostIp"=>"0.0.0.0", "HostPort"=>"31000"}]}
I, [2016-02-04T14:48:42.273542 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set pid_mode                    to "" (default value)
I, [2016-02-04T14:48:42.273585 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set privileged                  to false
I, [2016-02-04T14:48:42.273617 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set publish_all_ports           to false (default value)
I, [2016-02-04T14:48:42.273657 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set remove_volumes              to false (default value)
I, [2016-02-04T14:48:42.273706 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set restart_maximum_retry_count to 0 (default value)
I, [2016-02-04T14:48:42.273743 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set restart_policy              to "always"
I, [2016-02-04T14:48:42.273772 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set security_opts               to nil (default value)
I, [2016-02-04T14:48:42.273829 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set signal                      to "SIGTERM" (default value)
I, [2016-02-04T14:48:42.273857 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set tty                         to false (default value)
I, [2016-02-04T14:48:42.273898 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set ulimits                     to nil (default value)
I, [2016-02-04T14:48:42.273929 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set user                        to "" (default value)
I, [2016-02-04T14:48:42.273960 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set volumes                     to {}
I, [2016-02-04T14:48:42.273992 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     -   set volumes_from                to nil (default value)
I, [2016-02-04T14:48:42.602506 #31145]  INFO -- cd-docker-nethost-ubuntu-1404: 
I, [2016-02-04T14:48:42.609188 #31145]  INFO -- cd-docker-nethost-ubuntu-1404: 
I, [2016-02-04T14:48:42.613844 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:   * docker_container[app_net_host] action run
I, [2016-02-04T14:48:42.614297 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.614816 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     ================================================================================
I, [2016-02-04T14:48:42.727821 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     Error executing action `run` on resource 'docker_container[app_net_host]'
I, [2016-02-04T14:48:42.728345 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     ================================================================================
I, [2016-02-04T14:48:42.728665 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.729099 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     Chef::Exceptions::ValidationFailed
I, [2016-02-04T14:48:42.729554 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     ----------------------------------
I, [2016-02-04T14:48:42.730037 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     Cannot specify hostname, dns, dns_search, mac_address, or extra_hosts when network_mode is host.
I, [2016-02-04T14:48:42.730373 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.731474 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     Cookbook Trace:
I, [2016-02-04T14:48:42.732308 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     ---------------
I, [2016-02-04T14:48:42.733377 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:198:in `validate_container_create'
I, [2016-02-04T14:48:42.734030 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:317:in `block in <class:DockerContainer>'
I, [2016-02-04T14:48:42.736799 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
I, [2016-02-04T14:48:42.737441 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
I, [2016-02-04T14:48:42.738187 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.739408 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     Resource Declaration:
I, [2016-02-04T14:48:42.740847 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     ---------------------
I, [2016-02-04T14:48:42.749716 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     # In /tmp/kitchen/cookbooks/cd-docker/recipes/default.rb
I, [2016-02-04T14:48:42.751109 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.752651 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     127:   docker_container application_name do
I, [2016-02-04T14:48:42.754132 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     128:     repo image
I, [2016-02-04T14:48:42.754846 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     129:     tag version if version
I, [2016-02-04T14:48:42.756270 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     130:     container_name application_name
I, [2016-02-04T14:48:42.757730 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     131:     detach true
I, [2016-02-04T14:48:42.759075 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     132:     network_mode network_name
I, [2016-02-04T14:48:42.760581 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     133:     env envs
I, [2016-02-04T14:48:42.764423 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     134:     port ports
I, [2016-02-04T14:48:42.765946 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     135:     volume volumes
I, [2016-02-04T14:48:42.777525 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     136:     binds volumes
I, [2016-02-04T14:48:42.779185 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     137:     restart_policy 'always'
I, [2016-02-04T14:48:42.781102 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     138:     kill_after 30
I, [2016-02-04T14:48:42.782272 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     139:     privileged privileged_flag
I, [2016-02-04T14:48:42.783681 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     140:     command commandline if commandline
I, [2016-02-04T14:48:42.784205 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     141:   end
I, [2016-02-04T14:48:42.785448 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     142: 
I, [2016-02-04T14:48:42.786691 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.788121 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     Compiled Resource:
I, [2016-02-04T14:48:42.791991 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     ------------------
I, [2016-02-04T14:48:42.792913 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     # Declared in /tmp/kitchen/cookbooks/cd-docker/recipes/default.rb:127:in `block in from_file'
I, [2016-02-04T14:48:42.793363 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
I, [2016-02-04T14:48:42.794408 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     docker_container("app_net_host") do
I, [2016-02-04T14:48:42.794946 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       action [:run]
I, [2016-02-04T14:48:42.796183 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       updated true
I, [2016-02-04T14:48:42.800521 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       retries 0
I, [2016-02-04T14:48:42.802006 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       retry_delay 2
I, [2016-02-04T14:48:42.805023 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       default_guard_interpreter :default
I, [2016-02-04T14:48:42.805678 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       declared_type :docker_container
I, [2016-02-04T14:48:42.806357 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       cookbook_name :"cd-docker"
I, [2016-02-04T14:48:42.807712 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       recipe_name "default"
I, [2016-02-04T14:48:42.811996 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       repo "jmvrbanac/hastebin"
I, [2016-02-04T14:48:42.813516 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       container_name "app_net_host"
I, [2016-02-04T14:48:42.815622 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       detach true
I, [2016-02-04T14:48:42.816304 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       network_mode "host"
I, [2016-02-04T14:48:42.817517 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       env ["CLOUDESIRE_VHOST=nethost.cloudesire.local"]
I, [2016-02-04T14:48:42.828806 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       exposed_ports {"7777/tcp"=>{}}
I, [2016-02-04T14:48:42.829637 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       port_bindings {"7777/tcp"=>[{"HostIp"=>"0.0.0.0", "HostPort"=>"31000"}]}
I, [2016-02-04T14:48:42.830260 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       port ["31000:7777"]
I, [2016-02-04T14:48:42.831149 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       volumes_binds ["/etc/localtime:/etc/localtime:ro"]
I, [2016-02-04T14:48:42.832120 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       restart_policy "always"
I, [2016-02-04T14:48:42.832686 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       kill_after 30
I, [2016-02-04T14:48:42.834035 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       connection #<Docker::Connection:0x00000007caa100 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>60}>
I, [2016-02-04T14:48:42.840677 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       tag "latest"
I, [2016-02-04T14:48:42.841717 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       log_driver "json-file"
I, [2016-02-04T14:48:42.848060 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:       signal "SIGTERM"
I, [2016-02-04T14:48:42.848765 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     end
I, [2016-02-04T14:48:42.849427 #31145]  INFO -- cd-docker-nethost-ubuntu-1404:     
```

**Comment by someara** [comment]
The test recipe exercises the network_mode properties starting here.

https://github.com/chef-cookbooks/docker/blob/160e957cc6a4d2ee754131f6c21a1d7f80ae8469/test/cookbooks/docker_test/recipes/container.rb#L731-L761

Can you send a PR that sets up conditions to break the converge?

-s

**Comment by someara** [comment]
If not a PR, a comment works as well =)

**Comment by gionn** [comment]
I've added some ugly debug in the exception message:

```
diff --git a/libraries/docker_container.rb b/libraries/docker_container.rb
index d921471..b3b48df 100644
--- a/libraries/docker_container.rb
+++ b/libraries/docker_container.rb
@@ -195,7 +195,7 @@ module DockerCookbook
           property_is_set?(:mac_address) ||
           property_is_set?(:extra_hosts)
          )
-        fail Chef::Exceptions::ValidationFailed, 'Cannot specify hostname, dns, dns_search, mac_address, or extra_hosts when network_mode is host.'
+        fail Chef::Exceptions::ValidationFailed, "Cannot specify hostname #{property_is_set?(:hostname).to_s}, dns #{property_is_set?(:dns).to_s}, dns_search #{property_is_set?(:dns_search).to_s}, mac_address #{property_is_set?(:mac_address).to_s}, or extra_hosts #{property_is_set?(:extra_hosts).to_s} when network_mode is host."
       end
 
       if network_mode == 'container' &&
```

and then I've got:

```
       [2016-02-05T14:07:40+00:00] ERROR: docker_container[app_net_host] (cd-docker::default line 127) had an error: Chef::Exceptions::ValidationFailed: Cannot specify hostname false, dns true, dns_search true, ma
c_address false, or extra_hosts false when network_mode is host.
```

Actually I've not set any of those attributes on `docker_container`, but I've them added to `docker_service` resource, but `node['cloudesire']['infrastructure']` is false:

```
docker_service 'default' do
  storage_driver node['docker']['storage_driver']
  group node['docker']['group']
  version node['docker']['version']
  service_manager 'auto'
  install_method 'package'
  if node['cloudesire']['infrastructure']
    dns [ node['cd-docker']['default_network_gateway'], '8.8.8.8', '8.8.4.4' ]
    dns_search [ 'service.consul' ]
  end
  auto_restart true
  log_level :debug
  iptables node['docker']['iptables']
  action [:create, :start]
  if fw_service
    notifies :restart, fw_service
  end
end
```

Am I doing something wrong?

Thanks.

**Comment by gionn** [comment]
Please note that this happens only on first converge (or maybe, only when `docker_service` converge along with a `docker_container` with `network_mode 'host'`).

**Comment by gionn** [comment]
tested that now is working :+1:
