### ISSUE TITLE
First time image pull leads into an error (no image found)

### ISSUE THREAD

**Issue by cjohannsen81** [chef-cookbooks/docker#632]
First time of pulling an image leads to an error. Second run is successful then.

Here the log for the first run:

```
* docker_image[nginx] action pull
    
    ================================================================================
    Error executing action `pull` on resource 'docker_image[nginx]'
    ================================================================================
    
    Docker::Error::NotFoundError
    ----------------------------
    No such image: 6114b204585d
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.25.0/lib/docker/connection.rb:46:in `rescue in request'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.25.0/lib/docker/connection.rb:38:in `request'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.25.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.25.0/lib/docker/image.rb:126:in `get'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.25.0/lib/docker/image.rb:118:in `create'
    /var/chef/cache/cookbooks/docker/libraries/helpers_image.rb:71:in `block in pull_image'
    /var/chef/cache/cookbooks/docker/libraries/helpers_base.rb:57:in `with_retries'
    /var/chef/cache/cookbooks/docker/libraries/helpers_image.rb:66:in `pull_image'
    /var/chef/cache/cookbooks/docker/libraries/docker_image.rb:61:in `block in <class:DockerImage>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/simple_test/recipes/default.rb
    
     21: docker_image 'nginx' do
     22:   tag 'latest'
     23:   action :pull
     24:   notifies :redeploy, 'docker_container[my_nginx]'
     25: end
     26: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/simple_test/recipes/default.rb:21:in `from_file'
    
    docker_image("nginx") do
      action [:pull]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_image
      cookbook_name "simple_test"
      recipe_name "default"
      tag "latest"
      repo "nginx"
      connection #<Docker::Connection:0x00000005356808 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
    end
    

Running handlers:
[2016-02-08T08:54:05+01:00] ERROR: Running exception handlers
Running handlers complete
[2016-02-08T08:54:05+01:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 22 seconds
[2016-02-08T08:54:05+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-02-08T08:54:05+01:00] ERROR: docker_image[nginx] (simple_test::default line 21) had an error: Docker::Error::NotFoundError: No such image: 6114b204585d

[2016-02-08T08:54:05+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by gionn** [comment]
duplicated of #629
