### ISSUE TITLE
crash during docker_image pull_if_missing

### ISSUE THREAD

**Issue by AVVS** [chef-cookbooks/docker#655]
Action that triggers the errors, Docker version 1.10.1, build 9e83765

```
uname -r
3.19.0-28-generic
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

```
docker_image 'makeomatic/ms-users' do
  tag node[:cappasity_core][:ms_users][:version]
  action :pull_if_missing
end
```

Stack:

```
 * docker_image[makeomatic/ms-users] action pull_if_missing
    
    ================================================================================
    Error executing action `pull_if_missing` on resource 'docker_image[makeomatic/ms-users]'
    ================================================================================
    
    Docker::Error::NotFoundError
    ----------------------------
    No such image: f2967bc64886
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.24.1/lib/docker/connection.rb:46:in `rescue in request'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.24.1/lib/docker/connection.rb:38:in `request'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.24.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.24.1/lib/docker/image.rb:126:in `get'
    /var/chef/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.24.1/lib/docker/image.rb:118:in `create'
    /var/chef/cache/cookbooks/docker/libraries/helpers_image.rb:71:in `block in pull_image'
    /var/chef/cache/cookbooks/docker/libraries/helpers_base.rb:57:in `call'
    /var/chef/cache/cookbooks/docker/libraries/helpers_base.rb:57:in `with_retries'
    /var/chef/cache/cookbooks/docker/libraries/helpers_image.rb:66:in `pull_image'
    /var/chef/cache/cookbooks/docker/libraries/docker_image.rb:61:in `block in <class:DockerImage>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
    /var/chef/cache/cookbooks/docker/libraries/docker_image.rb:66:in `block in <class:DockerImage>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cappasity-core/recipes/ms-users.rb
    
     27: docker_image 'makeomatic/ms-users' do
     28:   tag node[:cappasity_core][:ms_users][:version]
     29:   action :pull_if_missing
     30: end
     31: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cappasity-core/recipes/ms-users.rb:27:in `from_file'
    
    docker_image("makeomatic/ms-users") do
      action [:pull_if_missing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_image
      cookbook_name "cappasity-core"
      recipe_name "ms-users"
      tag "5.6.0-1.9.0"
      repo "makeomatic/ms-users"
      connection #<Docker::Connection:0x000000086bdb10 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
    end
```

**Comment by AVVS** [comment]
On the next run it goes through just fine, btw

**Comment by someara** [comment]
What version of the Docker cookbook are you on? This was fixed in recent versions.

**Comment by AVVS** [comment]
@someara 

Using docker (2.5.5) from git://github.com/someara/chef-docker.git

**Comment by someara** [comment]
What chef-client version?

**Comment by AVVS** [comment]
Actually I've figured out the issue, thanks a lot for point in the right direction. I didn't upload updated dependency - compat_resource (12.7.3), so the cookbook was resolving to older version. On the latest version this didn't happen as you've said

Closing this as resolved, thanks again for your help
