### ISSUE TITLE
docker_installation_package fails on fedora22

### ISSUE THREAD

**Issue by sjsadowski** [chef-cookbooks/docker#699]
### Cookbook version

2.6.8
### Chef-client version

12.9.38
### Platform Details

[ssadowski@mgmt00 ~]$ cat /etc/redhat-release 
Fedora release 22 (Twenty Two)
[ssadowski@mgmt00 ~]$ uname -a
Linux mgmt00.clyx.io 4.5.0-x86_64-linode65 #2 SMP Mon Mar 14 18:01:58 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
### Scenario:

install docker from package
### Steps to Reproduce:

Create recipe that sets up docker repo, then try and install docker from a package, like so:

docker_installation_package 'default' do
    version '1.11.0'
    package_name 'docker-engine'
    action :create
end
### Expected Result:

install docker from package
### Actual Result:

Fails. Tries to use yum instead of dnf.
### Clipped output

```
  * docker_installation_package[default] action create
    * yum_package[docker-engine] action install[2016-04-27T10:02:50-04:00] WARN: Yum executable interpreter is /bin/bash. Falling back to default python.


      ================================================================================
      Error executing action `install` on resource 'yum_package[docker-engine]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
      STDOUT: 
      STDERR: Traceback (most recent call last):
        File "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py", line 36, in <module>
          import yum
      ImportError: No module named yum
      ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
      Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:123:in `compile_and_converge_action'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb

       17:       package package_name do
       18:         version package_version
       19:         options package_options
       20:         action :install
       21:       end
       22:     end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb:17:in `block in <class:DockerInstallationPackage>'

      yum_package("docker-engine") do
        package_name "docker-engine"
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :package
        cookbook_name "clyxio_docker"
        version "1.11.0"
        flush_cache {:before=>false, :after=>false}
      end

      Platform:
      ---------
      x86_64-linux


    ================================================================================
    Error executing action `create` on resource 'docker_installation_package[default]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    yum_package[docker-engine] (/var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb line 17) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
    STDOUT: 
    STDERR: Traceback (most recent call last):
      File "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py", line 36, in <module>
        import yum
    ImportError: No module named yum
    ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
    Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:123:in `compile_and_converge_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/clyxio_docker/recipes/default.rb

     18: docker_installation_package 'default' do
     19:     version '1.11.0'
     20:     package_name 'docker-engine'
     21:     action :create
     22: end
     23: 

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/clyxio_docker/recipes/default.rb:18:in `from_file'

    docker_installation_package("default") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_installation_package
      cookbook_name "clyxio_docker"
      recipe_name "default"
      version "1.11.0"
      package_name "docker-engine"
      package_version "1.11.0"
    end

    Platform:
    ---------
    x86_64-linux


Running handlers:
[2016-04-27T10:02:50-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-04-27T10:02:50-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2016-04-27T10:02:50-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-04-27T10:02:50-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-04-27T10:02:50-04:00] ERROR: docker_installation_package[default] (clyxio_docker::default line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: yum_package[docker-engine] (/var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb line 17) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py", line 36, in <module>
    import yum
ImportError: No module named yum
---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
[2016-04-27T10:02:50-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by tas50** [comment]
This is actually a Chef bug. We don't have a DNF provider for packages *yet*. It should be shipping in Chef 12.17 if all goes as planned.
