### ISSUE TITLE
Docker needs to be installed before successful chef-client run

### ISSUE THREAD

**Issue by cpressland** [chef-cookbooks/docker#718]
### Cookbook version

2.8.0
### Chef-client version

12.7.2
### Platform Details

CentOS 7.2 - Vagrant or DigitalOcean
### Scenario:

Basic Cookbook to install docker, pull an image, start the container fails.
### Steps to Reproduce:

Create a new cookbook and use this recipe:

```ruby
imgvars  = node['docker']['images']
contvars = node['docker']['containers']

directory '/data' do
  action :create
end

docker_service 'default' do
  action [:create, :start]
end

imgvars.each do |dimages|
  docker_image dimages[:name] do
    tag dimages[:tag]
    action :pull
  end
end

contvars.each do |containers|
 docker_container containers[:name] do
   repo containers[:repo]
   tag containers[:tag]
   port containers[:port]
   network_mode containers[:network_mode]
   links containers[:link]
   volumes containers[:volumes]
   env containers[:env]
   restart_policy 'always'
 end
end
```

And this attributes/default.rb

```ruby
default['docker']['images']    = [
  { :name=>"ghost", :tag=>"latest" },
  { :name=>"abiosoft/caddy", :tag=>"latest" }
]

default['docker']['containers'] = [
  { :name=>"ghost", :repo=>"ghost", :tag=>"latest", :port=>'2368:2368', :volumes=>"/data/ghost:/var/lib/ghost" },
  { :name=>"caddy", :repo=>"abiosoft/caddy", :tag=>"latest", :port=>['80:80', '443:443'], :volumes=>"/data/caddy/Caddyfile:/etc/Caddyfile" }
]
```
### Expected Result:

Docker should download the 'ghost' official image and start the container.
### Actual Result:

```
$ vagrant provision
==> default: Loading Berkshelf datafile...
==> default: Sharing cookbooks with VM
==> default: Updating Vagrant's Berkshelf...
==> default: Resolving cookbook dependencies...
==> default: Fetching 'dockertest' from source at .
==> default: Using compat_resource (12.10.6)
==> default: Using docker (2.8.0)
==> default: Using dockertest (0.1.0) from source at .
==> default: Vendoring compat_resource (12.10.6) to /Users/cpressland/.berkshelf/vagrant-berkshelf/shelves/berkshelf20160613-91532-b5ofu0-default/compat_resource
==> default: Vendoring docker (2.8.0) to /Users/cpressland/.berkshelf/vagrant-berkshelf/shelves/berkshelf20160613-91532-b5ofu0-default/docker
==> default: Vendoring dockertest (0.1.0) to /Users/cpressland/.berkshelf/vagrant-berkshelf/shelves/berkshelf20160613-91532-b5ofu0-default/dockertest
==> default: Chef 12.7.2 Omnibus package is already installed.
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: [2016-06-13T14:09:26+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.7.2
==> default: [2016-06-13T14:09:26+00:00] INFO: *** Chef 12.7.2 ***
==> default: [2016-06-13T14:09:26+00:00] INFO: Chef-client pid: 14509
==> default: [2016-06-13T14:09:27+00:00] INFO: Setting the run_list to ["recipe[dockertest::default]"] from CLI options
==> default: [2016-06-13T14:09:27+00:00] INFO: Run List is [recipe[dockertest::default]]
==> default: [2016-06-13T14:09:27+00:00] INFO: Run List expands to [dockertest::default]
==> default: [2016-06-13T14:09:27+00:00] INFO: Starting Chef Run for vagrant-3712a224
==> default: [2016-06-13T14:09:27+00:00] INFO: Running start handlers
==> default: [2016-06-13T14:09:27+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/dockertest/recipes/default.rb
==> default: ================================================================================
==> default:
==> default: Excon::Errors::SocketError
==> default: --------------------------
==> default: No such file or directory - connect(2) for /var/run/docker.sock (Errno::ENOENT)
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/docker/libraries/helpers_base.rb:44:in `api_version'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/docker/libraries/helpers_container.rb:61:in `default_network_mode'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/docker/libraries/docker_container.rb:65:in `block in <class:DockerContainer>'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:631:in `instance_exec'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:631:in `exec_in_resource'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:649:in `stored_value_to_output'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:365:in `get'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:278:in `call'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:521:in `network_mode'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/dockertest/recipes/default.rb:33:in `block (2 levels) in from_file'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `instance_eval'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `build'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/dockertest/recipes/default.rb:29:in `block in from_file'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/dockertest/recipes/default.rb:28:in `each'
==> default:   /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/dockertest/recipes/default.rb:28:in `from_file'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/2ebbc2eb034dc4b094e5584b61f5f05d/cookbooks/docker/libraries/helpers_base.rb:
==> default:
==> default:  37:        end
==> default:  38:
==> default:  39:        ################
==> default:  40:        # Helper methods
==> default:  41:        ################
==> default:  42:
==> default:  43:        def api_version
==> default:  44>>         @api_version ||= Docker.version(connection)['ApiVersion']
==> default:  45:        end
==> default:  46:
==> default:  47:        def connection
==> default:  48:          @connection ||= begin
==> default:  49:                            opts = {}
==> default:  50:                            opts[:read_timeout] = read_timeout if read_timeout
==> default:  51:                            opts[:write_timeout] = write_timeout if write_timeout
==> default:  52:
==> default:  53:                            if host =~ /^tcp:/
==> default:
==> default:
==> default: Running handlers:
==> default: [2016-06-13T14:09:28+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-06-13T14:09:28+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 01 seconds
==> default: [2016-06-13T14:09:28+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-06-13T14:09:28+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-06-13T14:09:28+00:00] ERROR: No such file or directory - connect(2) for /var/run/docker.sock (Errno::ENOENT)
==> default: [2016-06-13T14:09:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
### Workaround

Comment out the part of the recipe that performs docker related tasks, in this example:

```ruby
imgvars.each do |dimages|
  docker_image dimages[:name] do
    tag dimages[:tag]
    action :pull
  end
end

contvars.each do |containers|
 docker_container containers[:name] do
   repo containers[:repo]
   tag containers[:tag]
   port containers[:port]
   network_mode containers[:network_mode]
   links containers[:link]
   volumes containers[:volumes]
   env containers[:env]
   restart_policy 'always'
 end
end
```

Allow docker to successfully install and then remove the comments and re-run chef-client.

**Comment by cpressland** [comment]
After doing some further testing this only seems to occur when `network_mode containers[:network_mode]` is called. If I comment this from the above recipe everything seems to work fine.

**Comment by gmreburn** [comment]
Did you try setting :network_mode in default['docker']['containers'] for each container?

`network_mode` - Sets the networking mode for the container. One of `bridge`, `host`, `container`.

### attributes/default.rb

```
default['docker']['images']    = [
  { :name=>"ghost", :tag=>"latest" },
  { :name=>"abiosoft/caddy", :tag=>"latest" }
]

default['docker']['containers'] = [
  { :name=>"ghost", :repo=>"ghost", :tag=>"latest", :port=>'2368:2368', :volumes=>"/data/ghost:/var/lib/ghost", :network_mode=>"host" },
  { :name=>"caddy", :repo=>"abiosoft/caddy", :tag=>"latest", :port=>['80:80', '443:443'], :volumes=>"/data/caddy/Caddyfile:/etc/Caddyfile", :network_mode=>"host" }
]
```

**Comment by someara** [comment]
Confirmed api_version method requires docker to be running... it should never be used before then.
I also found another one of these in the docker_version method.

**Comment by someara** [comment]
Is this still an issue? I don't see the method in your stack trace actually being used anywhere anymore.

```
$ grep -ir api_version *
CHANGELOG.md:- _ Adding @api_version instance variable
libraries/helpers_base.rb:      def api_version
libraries/helpers_base.rb:        @api_version ||= Docker.version(connection)['ApiVersion']
spec/spec_helper.rb:    attr_accessor :api_version
spec/spec_helper.rb:    @api_version = '1.18'
$
```

**Comment by someara** [comment]
Closing this for now. Let me know if I need to re-open it.
