### ISSUE TITLE
GEM_PATH gets destroyed after installing `postgres` image

### ISSUE THREAD

**Issue by shireeshj** [chef-cookbooks/docker#725]
### Cookbook version

2.9.1

### Chef-client version

12.11.18

### Platform Details

Ubuntu 14.04 on amazon AWS

### Scenario:
[What you are trying to achieve and you can't?]
I am installing the `postgres` image from docker hub. using this cookbook. But after the cookbook completes, the gem bundler fails to run most likely because the GEM_PATH is erased.

My recipe has the following steps
---

```ruby
# --------------------------------
#  Restarting a container is a three step process and this method is fool proof as of now
#   Step 1: Stop the container by issueing "docker stop <container name>"
#   Step 2: Delete the container by issueing "docker rm <container name>"
#   Step 3: Run the container by issueing "docker run --name <container name> ...."
Chef::Log.info("install PostgreSQL database Sandbox Server")
Chef::Log.info("Pull PostgreSQL Docker image")
docker_image 'postgres' do
  tag "9.5"
  action :pull_if_missing
  notifies :redeploy, 'docker_container[postgres-sandbox]'
end

Chef::Log.info("Stop PostgreSQL Docker container if running")
docker_container 'postgres-sandbox' do
  action :stop
end

Chef::Log.info("Delete PostgreSQL Docker container if exists")
docker_container 'postgres-sandbox' do
  remove_volumes false
  action :delete
end

pg_password = node['postgres_root_password']

Chef::Log.info("Run a new PostgreSQL Docker container")
docker_container 'postgres-sandbox' do
  repo 'postgres'
  tag '9.5'
  detach true
  env ["POSTGRES_PASSWORD=#{pg_password}"]
  volumes [ "#{app_base_dir}/temp:/temp" ]
  action :run_if_missing
end
```

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

I am using `chef-solo` to run my cookbook.

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

When I run bundle command after this, I get this error
---

```sh
/usr/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 6 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/data/app/.gem/ruby/2.2.0:/var/lib/gems/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
	from /usr/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'
```

**Comment by shireeshj** [comment]
My apologies. Looks like the issue is not with the docker cookbook. Its something else...
