### ISSUE TITLE
NameError w/ CompatResource

### ISSUE THREAD

**Issue by ccampo133** [chef-cookbooks/docker#755]
### Cookbook version

2.9.5
### Chef-client version

12.14.89
### Platform Details

x_86_64-linux
### Scenario:

The cookbook straight up fails to compile. I'm trying to use some docker resources and I get the following error (in test kitchen):

```
Synchronizing Cookbooks:
         - mercury_queued (0.1.0)
         - java (1.42.0)
         - aws (3.4.1)
         - docker (2.9.5)
         - keepalived (2.1.1)
         - apt (4.0.2)
         - windows (2.0.2)
         - homebrew (2.1.2)
         - ohai (4.2.0)
         - build-essential (6.0.5)
         - seven_zip (2.0.2)
         - mingw (1.2.4)
         - compat_resource (12.14.0)
         - selinux (0.9.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       /tmp/kitchen/cache/cookbooks/compat_resource/libraries/chef_upstream_version.rb:2: warning: already initialized constant ChefCompat::CHEF_UPSTREAM_VERSION
       /tmp/kitchen/cache/cookbooks/compat_resource/libraries/chef_upstream_version.rb:2: warning: previous definition of CHEF_UPSTREAM_VERSION was here

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_base.rb
       ================================================================================

       NameError
       ---------
       uninitialized constant ChefCompat::Resource

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/docker/libraries/docker_base.rb:2:in `<module:DockerCookbook>'
         /tmp/kitchen/cache/cookbooks/docker/libraries/docker_base.rb:1:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/docker/libraries/docker_base.rb:

         1:  module DockerCookbook
         2>>   class DockerBase < ChefCompat::Resource
         3:      require_relative 'helpers_auth'
         4:      require_relative 'helpers_base'
         5:  
         6:      include DockerHelpers::Base
         7:  
         8:      #########
         9:      # Classes
        10:      #########
        11:  

       Platform:
       ---------
       x86_64-linux


       Running handlers:
       [2016-09-29T18:03:57+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-29T18:03:57+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 01 seconds
       [2016-09-29T18:03:57+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-29T18:03:57+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-29T18:03:57+00:00] ERROR: uninitialized constant ChefCompat::Resource
       [2016-09-29T18:03:57+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by nickkeyzer** [comment]
I'm seeing the exact same error while compiling as well. However, I'm using 2.9.6 instead.

**Cookbook version**
2.9.6

**Chef-client version**
12.14.89

**Platform Details**
x_86_64-linux

**Comment by nickkeyzer** [comment]
Referencing docker cookbook version 2.9.4 in my Berksfile allows the cookbook to compile successfully. 
`cookbook 'docker', '= 2.9.4'`

There must have been an issue introduced in 2.9.5 that still exists in 2.9.6 as well.

**Comment by tas50** [comment]
This should be fixed with changes to this cookbook.
