### ISSUE TITLE
Passing multiple volumes via attributes

### ISSUE THREAD

**Issue by cpressland** [chef-cookbooks/docker#769]
### Cookbook version
2.9.8

### Chef-client version
12.15.19

### Platform Details
VagrantBox, bento/ubuntu-16.04

### Scenario:
I'm attempting to pass multiple volumes to the docker_container, volume resource property via an attributes file.

### Steps to Reproduce:
The following attribute and recipe combo seems to work fine:

attributes/default.rb
```
# PHP Attributes
default['container']['php']['name'] = "php"
default['container']['php']['repo'] = "cpressland/php"
default['container']['php']['tag'] = "latest"
default['container']['php']['volume'] = "/data:/data"

default['dockertest']['containers'] = [
  { :name=>"#{node['container']['php']['name']}", :repo=>"#{node['container']['php']['repo']}", :tag=>"#{node['container']['php']['tag']}", :volume=>"#{node['container']['php']['volume']}" }
]
```
recipe/default.rb
```
containers = node['dockertest']['containers']

containers.each do |containers|
 docker_container containers[:name] do
   repo containers[:repo]
   tag containers[:tag]
   volume containers[:volume]
   restart_policy 'always'
 end
end
```

Additionally, passing the attribute inline works fine:

```
  { :name=>"#{node['container']['php']['name']}", :repo=>"#{node['container']['php']['repo']}", :tag=>"#{node['container']['php']['tag']}", :volume=>['/data:/data', '/data2:/data2'] }
```

However, adding multiple volumes causes an error.
```
default['container']['php']['volume'] = "'/data:/data', '/data2/data2'"
```
### Expected Result:
Multiple Volumes attached to docker container

### Actual Result:
```==> default: [2016-11-09T16:22:35+00:00] ERROR: docker_container[php] (dockertest::default line 29) had an error: Docker::Error::Server
Error: Invalid bind mount spec "'/data:/data', '/data2:/data2'": invalid mode: /data2'
```

**Comment by chasebolt** [comment]
default['container']['php']['volume'] = ['/data:/data', '/data2/data2']

It takes a string for a single volume or an array for multiple volumes.

**Comment by cpressland** [comment]
Thanks @chasebolt,

updated the attributes to look as follows:

```
# PHP Attributes
default['container']['php']['name'] = "php"
default['container']['php']['repo'] = "cpressland/php"
default['container']['php']['tag'] = "latest"
default['container']['php']['volume'] = ['/data:/data', '/data2:/data2']

default['dockertest']['containers'] = [
  { :name=>"#{node['container']['php']['name']}", :repo=>"#{node['container']['php']['repo']}", :tag=>"#{node['container']['php']['tag']}", :volume=>"#{node['container']['php']['volume']}" }
]
```

Throws the following error:

```
==> default: ================================================================================
==> default:
==> default: Error executing action `run` on resource 'docker_container[php]'
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default:
==> default:
==> default: Docker::Error::ServerError
==> default:
==> default: --------------------------
==> default:
==> default: Invalid bind mount spec "[\"/data:/data\", \"/data2:/data2\"]": invalid mode: /data2"]
==> default:
==> default:
==> default:
==> default:
==> default:
==> default: Cookbook Trace:
==> default:
==> default: ---------------
==> default:
==> default: /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:286:in `block (3 levels) in <class:DockerContainer>'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/docker/libraries/helpers_base.rb:66:in `with_retries'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:232:in `block (2 levels) in <class:DockerContainer>'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:81:in `converge_if_chang
ed'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:229:in `block in <class:DockerContainer>'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `instance_eval'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `compile_and_conv
erge_action'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:162:in `call_action'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:327:in `block in <class:DockerContainer>'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `instance_eval'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `compile_and_conv
erge_action'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in c
onverge'
==> default:
==> default:
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge
'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dockertest/recipes/default.rb
==> default:
==> default:      29:  docker_container containers[:name] do
==> default:      30:    repo containers[:repo]
==> default:      31:    tag containers[:tag]
==> default:      32:    volume containers[:volume]
==> default:      33:    restart_policy 'always'
==> default:      34:  end
==> default:      35: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dockertest/recipes/default.rb:29:in `block in from_file'
==> default:
==> default:     docker_container("php") do
==> default:       action [:run]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :docker_container
==> default:       cookbook_name "dockertest"
==> default:       recipe_name "default"
==> default:       repo "cpressland/php"
==> default:       tag "latest"
==> default:       volumes_binds ["[\"/data:/data\", \"/data2:/data2\"]"]
==> default:       restart_policy "always"
==> default:       container_name "php"
==> default:       connection #<Docker::Connection:0x000000054c3358 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_t
imeout=>60}>
==> default:       api_version "1.24"
==> default:       network_mode "default"
==> default:       signal "SIGTERM"
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:
==> default:
==> default: [2016-11-09T17:24:37+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2016-11-09T17:24:37+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default:
==> default: [2016-11-09T17:24:37+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 09 seconds
==> default: [2016-11-09T17:24:37+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-11-09T17:24:37+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-11-09T17:24:37+00:00] ERROR: docker_container[php] (dockertest::default line 29) had an error: Docker::Error::Server
Error: Invalid bind mount spec "[\"/data:/data\", \"/data2:/data2\"]": invalid mode: /data2"]
==> default: [2016-11-09T17:24:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code
 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Apologies if I'm missing something blindingly obvious here...

**Comment by chasebolt** [comment]
default['dockertest']['containers'] = [
  { :name=>"#{node['container']['php']['name']}",
:repo=>"#{node['container']['php']['repo']}",
:tag=>"#{node['container']['php']['tag']}",
*:volume=>"#{node['container']['php']['volume']}"* }
]

you are doing weird interpolation for no reason. this is adding quotes
making it a string again.

**Comment by cpressland** [comment]
sorry, I'm still learning chef and I wasn't aware there were other ways to call the attribute here... how exactly would I do that? I just can't seem to find anything to point me in the right direction.
