### ISSUE TITLE
Initial run of docker_service_manager 'default' raises error: undefined method `updated' for nil:NilClass 

### ISSUE THREAD

**Issue by spa-87** [chef-cookbooks/docker#774]
### Cookbook version
2.9.6 and 2.9.10

### Chef-client version
12.16.42

### Platform Details
AWS Ubuntu 14.04.03 (ami-a21529cc in Tokyo) 14.04.4 (ami-ba3e14d9 in Sydney; ami-26c43149 in Frankfurt)

### Scenario:
We use a wrapper cookbook above community docker cookbook for docker installation and configuration. Here's a piece of code which installs docker for us:
```
apt_repository 'docker' do
  uri          node[...]
  distribution node[...]
  components   node[...]
  keyserver    node[...]
  key          node[...]
end
docker_installation_package 'default' do
  version node[...]
  package_options "-o Dpkg::Options::='--force-confold'"
  action :create
end
docker_service_manager 'default' do
  action :start
end
```
It worked fine until we decided to upgrade Chef version from 12.6.0 to 12.16.42. For the new version we get an error: 

```
* docker_service_manager_upstart[default] action start
   * directory[/usr/lib/docker] action create (up to date)
   * template[/usr/lib/docker/docker-wait-ready] action create
        ...
   * template[/etc/default/docker] action create
        ...
   * docker_service_manager_upstart[default] action restart
     * service[docker] action stop
        - stop service service[docker]
     * directory[/usr/lib/docker] action create (up to date)
     * template[/usr/lib/docker/docker-wait-ready] action create (up to date)
     * template[/etc/init/docker.conf] action create (up to date)
     * template[/etc/default/docker] action create (up to date)
     * service[docker] action start
        - start service service[docker]

   * service[docker] action start (up to date)
    ================================================================================
    Error executing action `start` on resource 'docker_service_manager_upstart[default]'
    ================================================================================
       
    NoMethodError
    -------------
    undefined method `updated' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/___docker/recipes/install.rb

       30: docker_service_manager 'default' do
       31:   action :start
       32: end
       33: 
      
       Compiled Resource:
       ------------------
       # Declared in /var/chef/cache/cookbooks/___docker/recipes/install.rb:30:in `from_file'

      docker_service_manager_upstart("default") do
        action [:start]
        updated true
        updated_by_last_action true
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "___docker"
        recipe_name "install"
        pidfile "/var/run/docker.pid"
      end
      
      Platform:
      ---------
      x86_64-linux
```
At /var/chef/cache/chef-stacktrace.out I can see an error:
```
>>>> Caused by NoMethodError: undefined method `updated' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/data_collector.rb:202:in `resource_updated'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `resource_updated'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/provider.rb:166:in `set_updated_status'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/provider.rb:148:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```
We have retries for bootstrap and when chef-client run is triggered the second time, it runs fine, docker service is started and all seems to be ok:
```
* docker_service_manager_upstart[default] action start
* directory[/usr/lib/docker] action create (up to date)
* template[/usr/lib/docker/docker-wait-ready] action create (up to date)
* template[/etc/init/docker.conf] action create (up to date)
* template[/etc/default/docker] action create (up to date)
* service[docker] action start (up to date)
(up to date)
```
If I restore chef-client version at bootstrap command to 12.6.0, the problem disappears.

### Steps to Reproduce:
Launch EC2 instance from AMI `ami-26c43149` in Frankfurt and bootstrap it with `knife bootstrap ... --bootstrap-version 12.16.42`

### Expected Result:
Initial chef-client run fails.

**Comment by bitfag** [comment]
This looks similar to our issue.

OS: Ubuntu 16.04
Chef: 12.3.0
Cookbook version: 2.9.10

Just simple recipe:
```
docker_service 'default' do
   action [:create, :start]
end
```

Produces following error:
```
  * docker_service[default] action start[2016-11-22T16:21:02+05:00] INFO: Processing docker_service[default] action start (tgt-docker::default line 49)
[2016-11-22T16:21:02+05:00] WARN: Ambiguous resource precedence: [DockerCookbook::DockerServiceBase, DockerCookbook::DockerServiceManagerExecute, DockerCookbook::DockerServiceManagerSystemd, DockerCookbook::DockerServiceManagerUpstart], please use Chef.set_resource_priority_array to provide determinism
[2016-11-22T16:21:02+05:00] WARN: Ambiguous resource precedence: [DockerCookbook::DockerServiceBase, DockerCookbook::DockerServiceManagerExecute, DockerCookbook::DockerServiceManagerSystemd, DockerCookbook::DockerServiceManagerUpstart], please use Chef.set_resource_priority_array to provide determinism

    * docker_service_base[default] action start[2016-11-22T16:21:02+05:00] INFO: Processing docker_service_base[default] action start (/var/cache/chef/cookbooks/docker/libraries/docker_service.rb line 77)

      
      ================================================================================
      Error executing action `start` on resource 'docker_service_base[default]'
      ================================================================================
      
      NoMethodError
      -------------
      No resource or method named `action_start' for ` "default"'
      
      Cookbook Trace:
      ---------------
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:133:in `compile_and_converge_action'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      
      Resource Declaration:
      ---------------------
      # In /var/cache/chef/cookbooks/docker/libraries/docker_service.rb
      
       77:           svc = docker_service_manager(name, &block)
       78:         when 'execute'
       79:           svc = docker_service_manager_execute(name, &block)
       80:         when 'sysvinit'
       81:           svc = docker_service_manager_sysvinit(name, &block)
       82:         when 'upstart'
       83:           svc = docker_service_manager_upstart(name, &block)
       84:         when 'systemd'
       85:           svc = docker_service_manager_systemd(name, &block)
       86:         end
       87:         copy_properties_to(svc)
       88:         svc
       89:       end
       90:     end
       91: 
       92:     #########
       93:     # Actions
       94:     #########
       95: 
       96:     action :create do
       97:       validate_install_method
       98: 
       99:       installation do
      100:         action :create
      101:         notifies :restart, new_resource, :immediately
      102:       end
      103:     end
      104: 
      105:     action :delete do
      106:       installation do
      107:         action :delete
      108:       end
      109:     end
      110: 
      111:     action :start do
      112:       svc_manager do
      113:         action :start
      114:       end
      115:     end
      116: 
      117:     action :stop do
      118:       svc_manager do
      119:         action :stop
      120:       end
      121:     end
      122: 
      123:     action :restart do
      124:       svc_manager do
      125:         action :restart
      126:       end
      127:     end
      128:   end
      129: end
      
      Compiled Resource:
      ------------------
      # Declared in /var/cache/chef/cookbooks/docker/libraries/docker_service.rb:77:in `svc_manager'
      
      docker_cookbook::_docker_service_base("default") do
        action [:start]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "tgt-docker"
      end
      
[2016-11-22T16:21:02+05:00] INFO: Running queued delayed notifications before re-raising exception
    
    ================================================================================
    Error executing action `start` on resource 'docker_service[default]'
    ================================================================================
    
    NoMethodError
    -------------
    docker_service_base[default] (/var/cache/chef/cookbooks/docker/libraries/docker_service.rb line 77) had an error: NoMethodError: No resource or method named `action_start' for ` "default"'
    
    Cookbook Trace:
    ---------------
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:133:in `compile_and_converge_action'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/cache/chef/cookbooks/tgt-docker/recipes/default.rb
    
     49: docker_service 'default' do
     50:    action [:create, :start]
     51: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/cache/chef/cookbooks/tgt-docker/recipes/default.rb:49:in `from_file'
    
    docker_cookbook::_docker_service("default") do
      action [:create, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_service
      cookbook_name "tgt-docker"
      recipe_name "default"
      install_method "auto"
      service_manager "auto"
    end
    
[2016-11-22T16:21:02+05:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2016-11-22T16:21:02+05:00] ERROR: Running exception handlers
Running handlers complete
[2016-11-22T16:21:02+05:00] ERROR: Exception handlers complete
[2016-11-22T16:21:02+05:00] FATAL: Stacktrace dumped to /var/cache/chef/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.920087724 seconds
[2016-11-22T16:21:02+05:00] ERROR: docker_service[default] (tgt-docker::default line 49) had an error: NoMethodError: docker_service_base[default] (/var/cache/chef/cookbooks/docker/libraries/docker_service.rb line 77) had an error: NoMethodError: No resource or method named `action_start' for ` "default"'
[2016-11-22T16:21:02+05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by starx** [comment]
Same issue:

Ubuntu: 14.04 x64
Cookbook version: 2.9.7
Chef Client: 12.16.42

Usage:

```
docker_service 'default' do
	action [:create, :start]
end
```
Error:

```
================================================================================
  Error executing action `create` on resource 'docker_service[default]'
  ================================================================================
  
  NoMethodError
  -------------
  undefined method `updated' for nil:NilClass
  
  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/init/recipes/docker-install.rb
  
   19: docker_service 'default' do
   20: 	action [:create, :start]
   21: end
   22: 
  
  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/init/recipes/docker-install.rb:19:in `from_file'
  
  docker_service("default") do
    action [:create, :start]
    updated true
    updated_by_last_action true
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    declared_type :docker_service
    cookbook_name "init"
    recipe_name "docker-install"
    install_method "auto"
    service_manager "auto"
  end
  
  Platform:
  ---------
  x86_64-linux

```

And Trace:

```
Generated at 2016-11-22 11:22:01 +0000
NoMethodError: undefined method `failed' for nil:NilClass
Did you mean?  fail
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/data_collector.rb:210:in `resource_failed'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `resource_failed'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:634:in `rescue in run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:620:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'

>>>> Caused by NoMethodError: undefined method `updated' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/data_collector.rb:202:in `resource_updated'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `resource_updated'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/provider.rb:166:in `set_updated_status'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/provider.rb:148:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```

**Comment by starx** [comment]
Downgrading the cookbook to 2.9.2 (My previous working version) works

**Comment by spa-87** [comment]
I've solved this issue through Chef-client downgrading to 12.15.19 (this way is better for my use case as I faced with this issue in time of upgrading Chef-client from 12.6.0.)

**Comment by Fodoj** [comment]
Having the same issue, downgrading to 2.9.2 didn't really help

**Comment by Fodoj** [comment]
Most likely core chef bug, fixed here https://github.com/chef/chef/pull/5571

**Comment by gsaslis** [comment]
upgrading to chef-client 12.16.42 fixed this for me.

**Comment by someara** [comment]
I've updated the compat_resource dep to v2.12.0 to match the 12.16.42 bits.
This should be fixed up now.

Closing here.... please let me know if it needs to be re-opened.

-s
