### ISSUE TITLE
uninitialized constant DockerCookbook::ChefCompat redux

### ISSUE THREAD

**Issue by michaelshobbs** [chef-cookbooks/docker#789]
### Cookbook version
2.13.0

### Chef-client version
[2016-12-16T21:41:13+00:00] INFO: *** Chef 12.16.42 ***

### Platform Details
Ubuntu 14.04 on AWS OpsWorks

### Scenario:
Attempting to pull an image

### Steps to Reproduce:
NOTE: I never get close to this point as chef fails in compile

```ruby
docker_image 'gliderlabs/herokuish:latest' do
  action :pull
end
```

### Expected Result:
The chef run is compiled and the image is pulled

### Actual Result:
```
================================================================================
Recipe Compile Error in /var/chef/runs/4f913afb-27f4-4be7-b2b4-3e84b9c761a8/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb
================================================================================

NameError
---------
uninitialized constant DockerCookbook::ChefCompat
Did you mean?  ChefConfig

Cookbook Trace:
---------------
  /var/chef/runs/4f913afb-27f4-4be7-b2b4-3e84b9c761a8/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb:2:in `<module:DockerCookbook>'
  /var/chef/runs/4f913afb-27f4-4be7-b2b4-3e84b9c761a8/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/runs/4f913afb-27f4-4be7-b2b4-3e84b9c761a8/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb:

  1:  module DockerCookbook
  2>>   class DockerBase < ChefCompat::Resource
  3:      require_relative 'helpers_auth'
  4:      require_relative 'helpers_base'
  5:
  6:      include DockerHelpers::Base
  7:
  8:      #########
  9:      # Classes
 10:      #########
 11:

Platform:
---------
x86_64-linux
```

Unfortunately I'm still running into this after upgrading to the latest cookbook.
related to #757

**Comment by someara** [comment]
Very bizarre. Do you have an older version of `compat_resource` stuck in your cookbook cache somewhere? Maybe a Berksfile.lock needs an update?

**Comment by michaelshobbs** [comment]
I thought the same thing. It's a brand new EC2 instance. So no cache on the instance itself. I am vendoring with berkshelf but I do see that I have version `12.6.2` here and on my instance. Not sure what's up here. 😢 

local `Berksfile.lock`
```
DEPENDENCIES
  apt
  bluepill
  build-essential
  curl
  docker
  gem_specific_install
  git
  ohai
  python
  rsyslog
  runit
  sudo
  supervisor
  user
  xml
  yum
  yum-epel

GRAPH
  apt (5.0.0)
    compat_resource (>= 12.14.7)
  bluepill (3.0.0)
    rsyslog (>= 2.0)
  build-essential (7.0.2)
    compat_resource (>= 12.14)
    mingw (>= 1.1)
    seven_zip (>= 0.0.0)
  compat_resource (12.16.2)
  curl (2.0.3)
  dmg (3.0.0)
  docker (2.13.1)
    compat_resource (>= 12.16.2)
  gem_specific_install (0.2.4)
    git (>= 0.0.0)
  git (5.0.1)
    build-essential (>= 0.0.0)
    dmg (>= 0.0.0)
    yum-epel (>= 0.0.0)
  mingw (1.2.4)
    compat_resource (>= 0.0.0)
    seven_zip (>= 0.0.0)
  ohai (4.2.3)
    compat_resource (>= 12.14.7)
  packagecloud (0.2.5)
  python (1.4.6)
    build-essential (>= 0.0.0)
    yum-epel (>= 0.0.0)
  rsyslog (5.0.1)
    compat_resource (>= 12.14.6)
  runit (3.0.3)
    packagecloud (>= 0.0.0)
    yum-epel (>= 0.0.0)
  seven_zip (2.0.2)
    windows (>= 1.2.2)
  sudo (3.1.0)
  supervisor (0.4.12)
    python (>= 0.0.0)
  user (0.6.0)
  windows (2.1.1)
    ohai (>= 4.0.0)
  xml (3.1.0)
    build-essential (>= 0.0.0)
  yum (4.1.0)
  yum-epel (2.0.0)
    compat_resource (>= 12.14.6)
```

local `compat_resource`
```
cat compat_resource/metadata.json | jq
{
  "name": "compat_resource",
  "version": "12.16.2",
```

on instance `compat_resource` (metadata.json gets removed it seems)
```
head compat_resource/CHANGELOG.md
# compat_resource Cookbook CHANGELOG

This file is used to list changes made in each version of the compat_resource cookbook.

## 12.16.2 (2016-11-09)

- Sync chef-client changes from Chef 12.16.42

## 12.16.1 (2016-10-20)
```

**Comment by michaelshobbs** [comment]
ping...any thoughts on what i can try next?

**Comment by chasebolt** [comment]
Gist the full output of your chef run plus the trace log.

**Comment by michaelshobbs** [comment]
Sure thing. Here goes: 
- [chef run](https://gist.github.com/michaelshobbs/6c372e7e96a294a606e79b7d535b8142) 
- [trace](https://gist.github.com/michaelshobbs/7557016c708ac56ed7da5b11f8279458)

**Comment by chasebolt** [comment]
Loading cookbooks line does not show loading of the compat_resource
cookbook. This is your problem with the chef run. Not sure why it isn't
loading it as a dependency though.

**Comment by michaelshobbs** [comment]
Ah ha! Turns out I had `*.json` in my `.gitignore`. Testing again...

**Comment by michaelshobbs** [comment]
derp! I do believe this was my issue. Thanks for the assist!
