### ISSUE TITLE
docker_registry returns 400 malformed host header against Amazon ECR

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/docker#814]
### Cookbook version
2.14.0
### Chef-client version
12.5.1

### Platform Details
Amazon Linux 2016.09

### Scenario:
Call docker_registry against AWS ECR

### Steps to Reproduce:
Call docker_registry against ECR using a lazy initialized password:

```
docker_registry "https://#{node[:aws_account_id]}.dkr.ecr.#{node[:aws_region]}.amazonaws.com" do
  username "AWS"
  password lazy { node[:ecr_password] }
end
```

### Expected Result:
Logs in.

### Actual Result:
```
  * docker_registry[https://123456789012.dkr.ecr.us-east-1.amazonaws.com] action login
    
    ================================================================================
    Error executing action `login` on resource 'docker_registry[https://123456789012.dkr.ecr.us-east-1.amazonaws.com]'
    ================================================================================
    
    Docker::Error::ClientError
    --------------------------
    400 Bad Request: malformed Host header
    
    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_registry.rb:26:in `block in <class:DockerRegistry>'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `instance_eval'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `compile_and_converge_action'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/my_cookbook/recipes/batch_server.rb
    
     71: docker_registry "https://#{node[:aws_account_id]}.dkr.ecr.#{node[:aws_region]}.amazonaws.com" do
     72:   username "AWS"
     73:   password lazy { node[:ecr_password] }
     74: end
     75: 
    
    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/my_cookbook/recipes/batch_server.rb:71:in `from_file'
    
    docker_registry("https://123456789012.dkr.ecr.us-east-1.amazonaws.com") do
      action [:login]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_registry
      cookbook_name "my_cookbook"
      recipe_name "batch_server"
      username "AWS"
      password #<ChefCompat::CopiedFromChef::Chef::DelayedEvaluator:0x00000005eb17e8@/etc/chef/local-mode-cache/cache/cookbooks/my_cookbook/recipes/batch_server.rb:73>
      serveraddress "https://123456789012.dkr.ecr.us-east-1.amazonaws.com"
    end
    

Running handlers:
[2017-01-31T19:14:29+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-01-31T19:14:29+00:00] ERROR: Exception handlers complete
Chef Client failed. 32 resources updated in 42 seconds
[2017-01-31T19:14:29+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2017-01-31T19:14:29+00:00] ERROR: docker_registry[https://123456789012.dkr.ecr.us-east-1.amazonaws.com] (my_cookbook::batch_server line 71) had an error: Docker::Error::ClientError: 400 Bad Request: malformed Host header
[2017-01-31T19:14:30+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Not sure if this is caused by an issue with the docker-api gem, Amazon ECR, or this cookbook, but it only started happening since Docker 1.12.x from what I can tell.

I can login fine using a call to docker login on the command line.

**Comment by eric-tucker** [comment]
https://github.com/swipely/docker-api/issues/448

Looks like this cookbook needs to add additional values when calling `Docker.connection.post` in the docker_registry resource.

**Comment by eric-tucker** [comment]
@someara once I update the excon gem using a chef_gem call:

```
chef_gem "excon" do
  action :upgrade
  version "0.54.0"
end
```

I get a different error:

```
    Excon::Errors::SocketError
    --------------------------
    Connection reset by peer (Errno::ECONNRESET)
```

So progress?

**Comment by someara** [comment]
Closing this and linking to https://github.com/chef-cookbooks/docker/issues/826

**Comment by rashidmahmood** [comment]
Here is a workaround for this issue. 

1. Setup your access keys to your node. 
2. Add this to your recipe. It will simply login to ECR.  
cmd = "aws ecr get-login --region us-east-1"
value = `#{cmd}`
list = value.split(" ")

docker_registry 'AWS ECR registry' do
   serveraddress 'https://xyz.ecr.us-east-1.amazonaws.com'
   username 'AWS'
   password "#{list[5]}"
   email 'none'
end

**Comment by eric-tucker** [comment]
@rashidmahmood that's already what we are doing. It's not a permissions issue. This is logic that stopped working recently.
