### ISSUE TITLE
docker_container :run action always times out after 20 seconds, even when using timeout property

### ISSUE THREAD

**Issue by talcloudshare** [chef-cookbooks/docker#817]
## Cookbook version
2.13.0

### Chef-client version
12.17.44

### Platform Details
Ubuntu 16.04.1 LTS

### Scenario:
I am using docker_container resource, I started getting Docker::Error::TimeoutError: Container billing-app failed to change to running state after 20 seconds. I was trying to increase the timeout to 60 but no success.

### Steps to Reproduce:
Using the timeout property in docker_container resource

```
docker_container 'billing-app' do
  ...
  timeout 60
end
```

### Expected Result:
I am expecting the docker_container to wait 60 seconds for timeout and not 20

### Actual Result:
```
> chef-client -l debug
...
  * docker_container[billing-app] action run[2017-02-07T17:15:10+02:00] INFO: Processing docker_container[billing-app] action run (cs-nix-billing-app::default line 48)
[2017-02-07T17:15:10+02:00] DEBUG: Skipping update of docker_container[billing-app]: has not changed any of the specified properties ...


    ================================================================================
    Error executing action `run` on resource 'docker_container[billing-app]'
    ================================================================================

    Docker::Error::TimeoutError
    ---------------------------
    Container billing-app failed to change to running state after 20 seconds

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/docker/libraries/helpers_container.rb:88:in `wait_running_state'
    /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:316:in `block (2 levels) in <class:DockerContainer>'
    /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:311:in `block in <class:DockerContainer>'
    /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:167:in `call_action'
    /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:345:in `block in <class:DockerContainer>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cs-nix-billing-app/recipes/default.rb

     48: docker_container 'billing-app' do
     49:   repo '.../billing-app'
             ...
     62:   timeout 60
     63:   end
     64:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cs-nix-billing-app/recipes/default.rb:48:in `from_file'

    docker_container("billing-app") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_container
      ...
      timeout 60
      container_name "billing-app"
      connection #<Docker::Connection:0x00000003cdd748 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>60}>
      network_mode "default"
      api_version "1.24"
    end

    Platform:
    ---------
    x86_64-linux

[2017-02-07T17:15:31+02:00] INFO: Running queued delayed notifications before re-raising exception
[2017-02-07T17:15:31+02:00] DEBUG: Re-raising exception: Docker::Error::TimeoutError - docker_container[billing-app] (cs-nix-billing-app::default line 48) had an error: Docker::Error::TimeoutError: Container billing-app failed to change to running state after 20 seconds
/var/chef/cache/cookbooks/docker/libraries/helpers_container.rb:88:in `wait_running_state'
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:316:in `block (2 levels) in <class:DockerContainer>'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/mixin/why_run.rb:52:in `add_action'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:176:in `converge_by'
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:311:in `block in <class:DockerContainer>'
  (eval):2:in `block in action_start'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `compile_and_converge_action'
  (eval):2:in `action_start'
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:167:in `call_action'
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:345:in `block in <class:DockerContainer>'
  (eval):2:in `block in action_run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `compile_and_converge_action'
  (eval):2:in `action_run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:294:in `block in fork_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:247:in `block in run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `loop'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `interval_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:434:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:57:in `load'
  /usr/bin/chef-client:57:in `<main>'

Running handlers:
[2017-02-07T17:15:31+02:00] ERROR: Running exception handlers
Running handlers complete
[2017-02-07T17:15:31+02:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 30 seconds
[2017-02-07T17:15:31+02:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2017-02-07T17:15:31+02:00] DEBUG: Audit Reports are disabled. Skipping sending reports.
[2017-02-07T17:15:31+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-02-07T17:15:31+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-02-07T17:15:31+02:00] DEBUG: Docker::Error::TimeoutError: docker_container[billing-app] (cs-nix-billing-app::default line 48) had an error: Docker::Error::TimeoutError: Container billing-app failed to change to running state after 20 seconds
/var/chef/cache/cookbooks/docker/libraries/helpers_container.rb:88:in `wait_running_state'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:316:in `block (2 levels) in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:176:in `converge_by'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:311:in `block in <class:DockerContainer>'
(eval):2:in `block in action_start'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_start'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:167:in `call_action'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:345:in `block in <class:DockerContainer>'
(eval):2:in `block in action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'

>>>> Caused by Docker::Error::TimeoutError: Container billing-app failed to change to running state after 20 seconds
/var/chef/cache/cookbooks/docker/libraries/helpers_container.rb:88:in `wait_running_state'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:316:in `block (2 levels) in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:176:in `converge_by'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:311:in `block in <class:DockerContainer>'
(eval):2:in `block in action_start'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_start'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:167:in `call_action'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:345:in `block in <class:DockerContainer>'
(eval):2:in `block in action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'
[2017-02-07T17:15:31+02:00] ERROR: docker_container[billing-app] (cs-nix-billing-app::default line 48) had an error: Docker::Error::TimeoutError: Container billing-app failed to change to running state after 20 seconds
[2017-02-07T17:15:31+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by talcloudshare** [comment]
OK so I now found that I should use running_wait_time, but whatever value I set for it the action times out
When running with Docker CLI ad same parameters (docker run ...), it runs the container fairly quick
Not sure how to continue investigating

**Comment by talcloudshare** [comment]
Upgrading the cookbook to 2.14.3 seemed to resolve the issue
