### ISSUE TITLE
docker_registry doesn't honor http_proxy

### ISSUE THREAD

**Issue by gionn** [chef-cookbooks/docker#842]
### Cookbook version
2.14.4

### Chef-client version
12.6.0

### Platform Details
Ubuntu 14.04

### Scenario:
Use docker_registry resource to login to private docker registry

### Steps to Reproduce:
Use docker_registry resource on a node with no direct access to internet

### Expected Result:
Use http(s)_proxy properties passed to docker_service (pull works correctly)

### Actual Result:
```
   ================================================================================
   Error executing action `login` on resource 'docker_registry[https://***]'
   ================================================================================
   
   Docker::Error::TimeoutError
   ---------------------------
   read timeout reached
   
   Cookbook Trace:
   ---------------
   /home/fastweb/chef/gionn_chef/cookbooks/docker/libraries/docker_registry.rb:26:in `block in <class:DockerRegistry>'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `instance_eval'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:132:in `compile_and_converge_action'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
   /home/fastweb/chef/gionn_chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
   
   Resource Declaration:
   ---------------------
   # In /home/fastweb/chef/gionn_chef/cookbooks/cd-docker/recipes/default.rb
   
    32:     docker_registry "https://#{server}" do
    33:       username node['cloudesire']['registry']['username']
    34:       password node['cloudesire']['registry']['password']
    35:       email 'docker@cloudesire.com'
    36:       ignore_failure true
    37:     end
    38:   end

```

**Comment by gionn** [comment]
After further investigation, it looks like that was a dns timeout issue (solved removing all nameserver from resolv.conf).
