### ISSUE TITLE
docker_service fails on CentOS due to docker.socket issues

### ISSUE THREAD

**Issue by SaltwaterC** [chef-cookbooks/docker#897]
### Cookbook version

2.15.15 to 2.15.18

### Chef-client version

12.19.36 and 13.2.20

### Platform Details

CentOS 7.3

### Scenario:

Install and start a Docker service using:

```ruby
docker_service 'default' do
  host %w[tcp://0.0.0.0:2375]
  bip '172.17.42.1/16'
  storage_driver 'devicemapper'
  action %i[create start]
end
```

### Steps to Reproduce:

Run [kitchen-docker-host-vagrant](https://github.com/SaltwaterC/kitchen-docker-host-vagrant) with `rake up` and one of the affected versions.

### Expected Result:

```bash
echo $?
0
```

### Actual Result:

```bash
        ================================================================================
        Error executing action `run` on resource 'execute[systemctl restart docker]'
        ================================================================================

        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /bin/systemctl restart docker ----
        STDOUT:
        STDERR: Failed to restart docker.service: Unit is not loaded properly: Invalid argument.
        See system logs and 'systemctl status docker.service' for details.
        ---- End output of /bin/systemctl restart docker ----
        Ran /bin/systemctl restart docker returned 1

        Resource Declaration:
        ---------------------
        # In /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb

         90:       execute "systemctl restart #{docker_name}" do
         91:         command "/bin/systemctl restart #{docker_name}"
         92:         action :nothing
         93:       end
         94:

        Compiled Resource:
        ------------------
        # Declared in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb:90:in `block in <class:DockerServiceManagerSystemd>'

        execute("systemctl restart docker") do
          action [:nothing]
          default_guard_interpreter :execute
          command "/bin/systemctl restart docker"
          backup 5
          returns 0
          user nil
          declared_type :execute
          cookbook_name "kitchen-docker-host"
          domain nil
        end

        System Info:
        ------------
        chef_version=13.2.20
        platform=centos
        platform_version=7.3.1611
        ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
        program_name=chef-client worker: ppid=6825;start=17:00:59;
        executable=/opt/chef/bin/chef-client


             ================================================================================
             Error executing action `start` on resource 'docker_service_manager_systemd[default]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             execute[systemctl restart docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 90) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
             ---- Begin output of /bin/systemctl restart docker ----
             STDOUT:
             STDERR: Failed to restart docker.service: Unit is not loaded properly: Invalid argument.
             See system logs and 'systemctl status docker.service' for details.
             ---- End output of /bin/systemctl restart docker ----
             Ran /bin/systemctl restart docker returned 1

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb

       78:           svc = docker_service_manager(name, &block)
       79:         when 'execute'
       80:           svc = docker_service_manager_execute(name, &block)
       81:         when 'sysvinit'
       82:           svc = docker_service_manager_sysvinit(name, &block)
       83:         when 'upstart'
       84:           svc = docker_service_manager_upstart(name, &block)
       85:         when 'systemd'
       86:           svc = docker_service_manager_systemd(name, &block)
       87:         end
       88:         copy_properties_to(svc)
       89:         svc
       90:       end
       91:     end
       92:
       93:     #########
       94:     # Actions
       95:     #########
       96:
       97:     action :create do
       98:       validate_install_method
       99:
             100:       installation do
             101:         action :create
             102:         notifies :restart, new_resource, :immediately
             103:       end
             104:     end
             105:
             106:     action :delete do
             107:       installation do
             108:         action :delete
             109:       end
             110:     end
             111:
             112:     action :start do
             113:       svc_manager do
             114:         action :start
             115:       end
             116:     end
             117:
             118:     action :stop do
             119:       svc_manager do
             120:         action :stop
             121:       end
             122:     end
             123:
             124:     action :restart do
             125:       svc_manager do
             126:         action :restart
             127:       end
             128:     end
             129:   end
             130: end

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:78:in `svc_manager'

             docker_service_manager_systemd("default") do
        action [:start]
        updated true
        updated_by_last_action true
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "kitchen-docker-host"
        bip "172.17.42.1/16"
        host ["tcp://0.0.0.0:2375"]
        storage_driver ["devicemapper"]
        sane_paths ["/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin"]
        group "docker"
        pidfile "/var/run/docker.pid"
             end

             System Info:
             ------------
             chef_version=13.2.20
             platform=centos
             platform_version=7.3.1611
             ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
             program_name=chef-client worker: ppid=6825;start=17:00:59;
             executable=/opt/chef/bin/chef-client


           ================================================================================
           Error executing action `start` on resource 'docker_service[default]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           docker_service_manager_systemd[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 78) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[systemctl restart docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 90) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /bin/systemctl restart docker ----
           STDOUT:
           STDERR: Failed to restart docker.service: Unit is not loaded properly: Invalid argument.
           See system logs and 'systemctl status docker.service' for details.
           ---- End output of /bin/systemctl restart docker ----
           Ran /bin/systemctl restart docker returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/kitchen-docker-host/recipes/default.rb

            12: docker_service 'default' do
            13:   host %w[tcp://0.0.0.0:2375]
            14:   bip '172.17.42.1/16'
            15:   storage_driver 'devicemapper'
            16:   action %i[create start]
            17: end
            18:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/kitchen-docker-host/recipes/default.rb:12:in `from_file'

           docker_service("default") do
             action [:create, :start]
             updated true
             updated_by_last_action true
             default_guard_interpreter :default
             declared_type :docker_service
             cookbook_name "kitchen-docker-host"
             recipe_name "default"
             host ["tcp://0.0.0.0:2375"]
             bip "172.17.42.1/16"
             storage_driver ["devicemapper"]
             group "docker"
             pidfile "/var/run/docker.pid"
           end

           System Info:
           ------------
           chef_version=13.2.20
           platform=centos
           platform_version=7.3.1611
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=6825;start=17:00:59;
           executable=/opt/chef/bin/chef-client
```

### Post mortem:

I'm not sure whether this is related to #894 or even a duplicate as in this scenario the docker-ce.repo is being used rather than the CentOS repository. However, I've tracked the systemd fail to start the docker.service unit down to the docker.socket unit which isn't configured correctly. This might indicate that the issue is indeed a duplicate of #894. However, the issue started since 2.15.15 rather than 2.15.18.

Fixing the docker.socker unit doesn't really fix anything as systemd would listen on the configured socket which would prevent Docker from binding. The simplest way of getting rid of the issue is to remove the docker.socket reference from docker.service.

In fact, the docker.socket unit is actually broken in the previous releases as the ListenStream won't accept `tcp://0.0.0.0:2375` as a proper value. I see the diff from 2.15.14 to the broken versions is adding docker as group (which should be benign) and changing the .socket references to docker.socket which actually pulls the bad conf into docker.service.

**Comment by chasebolt** [comment]
please gist your docker.socket and docker.service files

**Comment by SaltwaterC** [comment]
Sure thing: https://gist.github.com/SaltwaterC/dd929f4ddb3bbc9089168b24068a06f0

**Comment by chasebolt** [comment]
do you have a group called `docker` or `dockerroot`?

**Comment by SaltwaterC** [comment]
There is docker:

```bash
[vagrant@kdh-centos-73 ~]$ cat /etc/group | grep docker
docker:x:992:
```

This is being created by the docker-ce package. However, I've already stated which is the actual issue with the docker.socket unit on [ListenStream](https://www.freedesktop.org/software/systemd/man/systemd.socket.html) that's getting pulled into docker.service which is not group related:

```bash
[root@kdh-centos-73 ~]# systemctl start docker.socket
Failed to start docker.socket: Unit is not loaded properly: Invalid argument.
See system logs and 'systemctl status docker.socket' for details.
[root@kdh-centos-73 ~]# systemctl status docker.socket
● docker.socket - Docker Socket for the API
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Jul 28 18:22:03 kdh-centos-73.vagrantup.com systemd[1]: [/etc/systemd/system/docker.socket:6] Failed to parse address value, ignoring: tcp://0.0.0.0:2375
Jul 28 18:22:03 kdh-centos-73.vagrantup.com systemd[1]: docker.socket lacks Listen setting. Refusing.
```

The value is completely FUBAR'd as it isn't what systemd is expecting. If I do fix the ListStream, i.e:

```bash
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=0.0.0.0:2375
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```

Then the docker.service is bit unhappy:

```bash
[root@kdh-centos-73 ~]# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[root@kdh-centos-73 ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2017-07-28 18:28:41 UTC; 2s ago
     Docs: https://docs.docker.com
  Process: 6121 ExecStart=/usr/bin/dockerd --bip=172.17.42.1/16 --group=docker -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --storage-driver=devicemapper (code=exited, status=1/FAILURE)
  Process: 6118 ExecStartPre=/sbin/sysctl -w net.ipv6.conf.all.forwarding=1 (code=exited, status=0/SUCCESS)
  Process: 6116 ExecStartPre=/sbin/sysctl -w net.ipv4.ip_forward=1 (code=exited, status=0/SUCCESS)
 Main PID: 6121 (code=exited, status=1/FAILURE)

Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: Failed to start Docker Application Container Engine.
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: Unit docker.service entered failed state.
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: docker.service failed.
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: docker.service holdoff time over, scheduling restart.
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: start request repeated too quickly for docker.service
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: Failed to start Docker Application Container Engine.
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: Unit docker.service entered failed state.
Jul 28 18:28:41 kdh-centos-73.vagrantup.com systemd[1]: docker.service failed.
```

This bit gives a hint about the reason:

```bash
[root@kdh-centos-73 ~]# netstat -tulnp | grep 2375
tcp        0      0 0.0.0.0:2375            0.0.0.0:*               LISTEN      1/systemd
```

And of course, docker itself refuses to start for reasons I've already explained in the post mortem:

```bash
[root@kdh-centos-73 ~]# /usr/bin/dockerd --bip=172.17.42.1/16 --group=docker -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --storage-driver=devicemapper
WARN[0000] [!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]
listen tcp 0.0.0.0:2375: bind: address already in use
```
