### ISSUE TITLE
had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 96)

### ISSUE THREAD

**Issue by josephmicheal** [chef-cookbooks/docker#899]
### Chef-client version
*** Chef 12.21.3 ***

### Platform Details
Red Hat Enterprise Linux Server release 7.3 (Maipo)

### Scenario:
When we do chef-client it breaks which was working without issues 2 weeks agao.

### Steps to Reproduce:
Based on the Docker version it breaks I believe this version breaks.

### Expected Result:
Cookbook should run without issues.

### Log
[2017-08-01T02:00:34-05:00] INFO: Forking chef instance to converge...
[2017-08-01T02:00:34-05:00] INFO: *** Chef 12.21.3 ***
[2017-08-01T02:00:34-05:00] INFO: Platform: x86_64-linux
[2017-08-01T02:00:34-05:00] INFO: Chef-client pid: 6093
[2017-08-01T02:00:34-05:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2017-08-01T02:00:42-05:00] INFO: Run List is [recipe[myapp_cookbook]]
[2017-08-01T02:00:42-05:00] INFO: Run List expands to [myapp_cookbook]
[2017-08-01T02:00:42-05:00] INFO: Starting Chef Run for myapp-node
[2017-08-01T02:00:42-05:00] INFO: Running start handlers
[2017-08-01T02:00:42-05:00] INFO: Start handlers complete.
[2017-08-01T02:00:42-05:00] INFO: HTTP Request Returned 404 Not Found: 
[2017-08-01T02:00:42-05:00] INFO: Error while reporting run start to Data Collector. URL: https://chef001.mycompany.com/organizations/myapp/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
[2017-08-01T02:00:42-05:00] INFO: Loading cookbooks [yum@5.0.1, certs_tgt@2.2.2, tpm@2.0.2, now@1.0.0, ohai@5.1.0, rhn@0.1.1, rhn-tgt@2.0.0, compat_resource@12.19.0, docker@2.15.18, chef-vault@3.0.0, myapp_cookbook@1.1.8, ctm_agent@1.0.3, windows@3.1.1]
[2017-08-01T02:00:45-05:00] INFO: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using chef-vault 3.2.0
Using bundler 1.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

[2017-08-01T02:00:45-05:00] INFO: HTTP Request Returned 404 Not Found: 
[2017-08-01T02:00:45-05:00] INFO: Processing docker_service[default] action create (myapp_cookbook::default line 23)
[2017-08-01T02:00:45-05:00] INFO: Processing docker_installation_tarball[default] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 66)
[2017-08-01T02:00:45-05:00] WARN: Default value nil is invalid for property checksum of resource docker_installation_tarball. Possible fixes: 1. Remove 'default: nil' if nil means 'undefined'. 2. Set a valid default value if there is a reasonable one. 3. Allow nil as a valid value of your property (for example, 'property :checksum, [ String, nil ], default: nil'). Error: Property checksum must be one of: String!  You passed nil. (CHEF-5)/var/chef/cache/cookbooks/docker/libraries/docker_installation_tarball.rb:26:in `block (2 levels) in <class:DockerInstallationTarball>'.
Please see https://docs.chef.io/deprecations_custom_resource_cleanups.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
[2017-08-01T02:00:45-05:00] INFO: Processing remote_file[/var/chef/cache/docker-1.12.3.tgz] action create (/var/chef/cache/cookbooks/docker/libraries/docker_installation_tarball.rb line 24)
[2017-08-01T02:00:46-05:00] INFO: Processing execute[extract tarball] action nothing (/var/chef/cache/cookbooks/docker/libraries/docker_installation_tarball.rb line 34)
[2017-08-01T02:00:46-05:00] INFO: Processing docker_service[default] action start (myapp_cookbook::default line 23)
[2017-08-01T02:00:46-05:00] INFO: Processing docker_service_manager_systemd[default] action start (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 78)
[2017-08-01T02:00:46-05:00] INFO: Processing directory[/usr/libexec/docker] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service_base.rb line 100)
[2017-08-01T02:00:46-05:00] INFO: Processing template[/usr/libexec/docker/docker-wait-ready] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service_base.rb line 107)
[2017-08-01T02:00:46-05:00] INFO: Processing template[/lib/systemd/system/docker.socket] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 23)
[2017-08-01T02:00:46-05:00] INFO: Processing template[/lib/systemd/system/docker.service] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 38)
[2017-08-01T02:00:46-05:00] INFO: Processing template[/etc/systemd/system/docker.socket] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 52)
[2017-08-01T02:00:46-05:00] INFO: Processing template[/etc/systemd/system/docker.service] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 66)
[2017-08-01T02:00:46-05:00] INFO: Processing execute[systemctl daemon-reload] action nothing (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 84)
[2017-08-01T02:00:46-05:00] INFO: Processing execute[systemctl restart docker] action nothing (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 90)
[2017-08-01T02:00:46-05:00] INFO: Processing service[docker] action enable (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 96)
[2017-08-01T02:00:46-05:00] INFO: Processing service[docker] action start (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 96)

================================================================================
[31mError executing action `start` on resource 'service[docker]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system start docker ----
STDOUT: 
STDERR: A dependency job for docker.service failed. See 'journalctl -xe' for details.
---- End output of /usr/bin/systemctl --system start docker ----
Ran /usr/bin/systemctl --system start docker returned 1

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb

 96:       service docker_name do
 97:         provider Chef::Provider::Service::Systemd
 98:         supports status: true
 99:         action [:enable, :start]
100:         only_if { ::File.exist?("/lib/systemd/system/#{docker_name}.service") }
101:       end
102:     end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb:96:in `block in <class:DockerServiceManagerSystemd>'

service("docker") do
  provider Chef::Provider::Service::Systemd
  action [:enable, :start]
  supports {:status=>true}
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  service_name "docker"
  enabled true
  running false
  masked false
  pattern "docker"
  declared_type :service
  cookbook_name "myapp_cookbook"
  only_if { #code block }
end

System Info:
------------
chef_version=12.21.3
platform=redhat
platform_version=7.3
ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
program_name=chef-client worker: ppid=6088;start=02:00:34;
executable=/opt/chef/bin/chef-client

[2017-08-01T02:00:47-05:00] INFO: Running queued delayed notifications before re-raising exception

================================================================================
[31mError executing action `start` on resource 'docker_service_manager_systemd[default]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
service[docker] (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 96) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system start docker ----
STDOUT: 
STDERR: A dependency job for docker.service failed. See 'journalctl -xe' for details.
---- End output of /usr/bin/systemctl --system start docker ----
Ran /usr/bin/systemctl --system start docker returned 1

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/docker/libraries/docker_service.rb

 78:           svc = docker_service_manager(name, &block)
 79:         when 'execute'
 80:           svc = docker_service_manager_execute(name, &block)
 81:         when 'sysvinit'
 82:           svc = docker_service_manager_sysvinit(name, &block)
 83:         when 'upstart'
 84:           svc = docker_service_manager_upstart(name, &block)
 85:         when 'systemd'
 86:           svc = docker_service_manager_systemd(name, &block)
 87:         end
 88:         copy_properties_to(svc)
 89:         svc
 90:       end
 91:     end
 92: 
 93:     #########
 94:     # Actions
 95:     #########
 96: 
 97:     action :create do
 98:       validate_install_method
 99: 
100:       installation do
101:         action :create
102:         notifies :restart, new_resource, :immediately
103:       end
104:     end
105: 
106:     action :delete do
107:       installation do
108:         action :delete
109:       end
110:     end
111: 
112:     action :start do
113:       svc_manager do
114:         action :start
115:       end
116:     end
117: 
118:     action :stop do
119:       svc_manager do
120:         action :stop
121:       end
122:     end
123: 
124:     action :restart do
125:       svc_manager do
126:         action :restart
127:       end
128:     end
129:   end
130: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/docker/libraries/docker_service.rb:78:in `svc_manager'

docker_service_manager_systemd("default") do
  action [:start]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :docker_service_manager
  cookbook_name "myapp_cookbook"
  host ["tcp://0.0.0.0:4243", "unix:///var/run/docker.sock"]
  group "dockerroot"
  pidfile "/var/run/docker.pid"
  logfile "/var/log/docker.log"
end

System Info:
------------
chef_version=12.21.3
platform=redhat
platform_version=7.3
ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
program_name=chef-client worker: ppid=6088;start=02:00:34;
executable=/opt/chef/bin/chef-client

[2017-08-01T02:00:47-05:00] INFO: Running queued delayed notifications before re-raising exception

================================================================================
[31mError executing action `start` on resource 'docker_service[default]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
docker_service_manager_systemd[default] (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 78) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 96) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system start docker ----
STDOUT: 
STDERR: A dependency job for docker.service failed. See 'journalctl -xe' for details.
---- End output of /usr/bin/systemctl --system start docker ----
Ran /usr/bin/systemctl --system start docker returned 1

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/myapp_cookbook/recipes/default.rb

 23: docker_service 'default' do
 24:    version '1.12.3'
 25:    install_method 'tarball'
 26:    host [ "tcp://0.0.0.0:4243", 'unix:///var/run/docker.sock' ]
 27:    action [:create, :start]
 28: end
 29: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/myapp_cookbook/recipes/default.rb:23:in `from_file'

docker_service("default") do
  action [:create, :start]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :docker_service
  cookbook_name "myapp_cookbook"
  recipe_name "default"
  version "1.12.3"
  install_method "tarball"
  host ["tcp://0.0.0.0:4243", "unix:///var/run/docker.sock"]
  service_manager "auto"
  group "dockerroot"
  pidfile "/var/run/docker.pid"
  logfile "/var/log/docker.log"
end

System Info:
------------
chef_version=12.21.3
platform=redhat
platform_version=7.3
ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
program_name=chef-client worker: ppid=6088;start=02:00:34;
executable=/opt/chef/bin/chef-client

[2017-08-01T02:00:47-05:00] INFO: Running queued delayed notifications before re-raising exception
[2017-08-01T02:00:47-05:00] ERROR: Running exception handlers
[2017-08-01T02:00:47-05:00] ERROR: Exception handlers complete
[2017-08-01T02:00:47-05:00] INFO: Sending resource update report (run-id: 00d63d8b-7a5d-4703-be68-7c12fc99154b)
[2017-08-01T02:00:47-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-08-01T02:00:47-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-01T02:00:47-05:00] ERROR: docker_service[default] (myapp_cookbook::default line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_systemd[default] (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 78) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb line 96) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system start docker ----
STDOUT: 
STDERR: A dependency job for docker.service failed. See 'journalctl -xe' for details.
---- End output of /usr/bin/systemctl --system start docker ----
Ran /usr/bin/systemctl --system start docker returned 1
[2017-08-01T02:00:47-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by runecalico** [comment]
Version 12.15.17 and later introduced a change to the systemd service file that will break all versions of RedHat as it requires a version of Systemd that isn't available for RHEL/Centos.  You can get around this by pinning the docker cookbook in your metadata.rb to 12.15.16 or earlier.  It's the TasksMax=infinity line in the systemd config (/etc/systemd/system/docker.service).  You need systemd 226 or greater to support that  line/field, and the cookbook doesn't check if you have systemd 226 or greater, it's just enabled... and there is no way (that I could see) in the current release of the cookbook to disable it.

**Comment by runecalico** [comment]
if you look in /var/log/daemon.log you would see this message: 
[/etc/systemd/system/docker.service:21] Unknown lvalue 'TasksMax' in section 'Service'

**Comment by chasebolt** [comment]
can you please explain how it is breaking? systemd will output that unknown value and simply ignore it - it shouldnt be actually failing.

**Comment by chasebolt** [comment]
@josephmicheal please see https://github.com/chef-cookbooks/docker#docker-group. i believe this is your issue.

**Comment by runecalico** [comment]
@chasebolt  Thanks for the tip, I was completely off with why 12.15.16+ is breaking *my* docker deployments. You are correct, the TASKSMAX section, which while only supported systems with systemd greater then 226, doesn't in fact stop a docker service from running.   Did 12.15.16+ introduce setting docker group to dockerroot by default for all installs on Centos/Redhat? I *am* using the RPM's maintained by docker, and NOT the one's by redhat. However after some digging, I noticed that starting with 12.15.16, my cookbook deployment of docker-engine (from the moby maintained repo) no longer works on RHEL 7.3, and it seems like I'm getting this dockerroot group thing... which of course doesn't exist because I'm not running the RedHat maintained RPM's. I haven't looked to see everything that's different (between 12.15.16 and 12.15.16), but the docker group being set I did notice, and seems to have started with 12.15.16+.

**Comment by chasebolt** [comment]
If you are using Redhat's maintained docker you need to set the group property on your service block. If you are using Docker's official repo you don't need to set anything as this cookbook defaults to the correct group. There is a new section on the README covering this.

**Comment by chasebolt** [comment]
closing for now as OP hasn't responded. please reopen with the requested info when you get time.
