### ISSUE TITLE
Recipe compile error - cannot load such file -- docker

### ISSUE THREAD

**Issue by kishaningithub** [chef-cookbooks/docker#986]
```bash
================================================================================
Recipe Compile Error in /var/folders/57/d256bszn1pd1s2v2xyv94xxc0000gn/T/d20180327-21896-ikxtyl/cookbooks/docker/libraries/docker_base.rb
================================================================================

LoadError
---------
cannot load such file -- docker

Cookbook Trace:
---------------
  /var/folders/57/d256bszn1pd1s2v2xyv94xxc0000gn/T/d20180327-21896-ikxtyl/cookbooks/docker/libraries/docker_base.rb:3:in `require'
  /var/folders/57/d256bszn1pd1s2v2xyv94xxc0000gn/T/d20180327-21896-ikxtyl/cookbooks/docker/libraries/docker_base.rb:3:in `<class:DockerBase>'
  /var/folders/57/d256bszn1pd1s2v2xyv94xxc0000gn/T/d20180327-21896-ikxtyl/cookbooks/docker/libraries/docker_base.rb:2:in `<module:DockerCookbook>'
  /var/folders/57/d256bszn1pd1s2v2xyv94xxc0000gn/T/d20180327-21896-ikxtyl/cookbooks/docker/libraries/docker_base.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/folders/57/d256bszn1pd1s2v2xyv94xxc0000gn/T/d20180327-21896-ikxtyl/cookbooks/docker/libraries/docker_base.rb:

  1:  module DockerCookbook
  2:    class DockerBase < Chef::Resource
  3>>     require 'docker'
  4:      require 'shellwords'
  5:
  6:      ##########
  7:      # coersion
  8:      ##########
  9:
 10:      def coerce_labels(v)
 11:        case v
 12:        when Hash, nil

System Info:
------------
chef_version=12.21.1
platform=centos
platform_version=6.8
ruby=ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
program_name=/Users/kishanb/.rvm/gems/ruby-2.2.3@chef-repo/bin/rspec
executable=/Users/kishanb/.rvm/gems/ruby-2.2.3@chef-repo/bin/ruby_executable_hooks
```

**Comment by kishaningithub** [comment]
Putting `gem 'docker-api'` in my Gemfile fixed the issue for me

**Comment by chandru9279** [comment]
Bump. Me and Balaji faced this same issue :)

**Comment by tas50** [comment]
What’s version of Chef are you on?

**Comment by kishaningithub** [comment]
@tas50
Chef server version -> 12.16.14
Chef client version  ->  12.11.18
